# Paquetes y módulos

In [5]:
# Importar paquete modulo.py previamente descargado
from modulo import *

In [2]:
saludo()

saludo desde paquete


In [3]:
funcion()

otra funcion


In [4]:
suma(2, 3)

5

## Paquete NumPy

Es un paquete enfocado en manipular información en estructuras conocidas como vectores, arreglos y matrices. La contribución más significativa del paquete es la introducción de un nuevo tipo de dato → array.

In [10]:
!py -m pip install numpy # Instalar paquete numpy

   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
    --------------------------------------- 0.3/12.8 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.8 MB 907.0 kB/s eta 0:00:14
   - -------------------------------------- 0.5/12.8 MB 907.0 kB/s eta 0:00:14
   - -------------------------------------- 0.5/12.8 MB 907.0 kB/s eta 0:00:14
   -- ------------------------------------- 0.8/12.8 MB 617.3 kB/s eta 0:00:20
   --- ------------------------------------ 1.0/12.8 MB 701.1 kB/s eta 0:00:17
   --- ------------------------------------ 1.0/12.8 MB 701.1 kB/s eta 0:00:17
   ---- ----------------------------------- 1.3/12.8 MB 689.7 kB/s eta 0:00:17
   ---- ----------------------------------- 1.3/12.8 MB 689.7 kB/s eta 0:00:17
   ---- ----------

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [12]:
import numpy as np

In [13]:
lista = [3,4,5]
variable = np.array(lista)
type(variable)

numpy.ndarray

Arreglo: lista de datos numéricos unidimensional (vector).
Matriz: colección de datos numéricos en dos dimensiones (filas y columnas).

En Python puro no existen "arreglos" como tal, sino listas (list) y tuplas (tuple).
En NumPy, tanto los vectores como las matrices y tensores se representan con la misma estructura: numpy.ndarray. → En Python (con NumPy) son todos arreglos (ndarray), que pueden ser unidimensionales (vector), bidimensionales (matriz) o de más dimensiones (tensor).

In [14]:
# .ndim permite conocer la dimensión del array
variable.ndim

1

In [17]:
variable2d = np.array([
    [4,5,6],
    [7,8,9]
]) # Crear un array. Como la entrada es una lista de listas, NumPy lo interpreta como una matriz 2D.
type(variable2d), variable2d.ndim, variable2d.shape # .shape devuelve la forma del array: (n_filas, n_columnas)

(numpy.ndarray, 2, (2, 3))

In [18]:
variable2d

array([[4, 5, 6],
       [7, 8, 9]])

### ¿Qué funciones tiene el paquete NumPy?

In [20]:
# Arrays de ceros
np.zeros(6), np.zeros([3,4])

(array([0., 0., 0., 0., 0., 0.]),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]))

In [21]:
# Arrays de unos
np.ones(4), np.ones((2,3,4)) # Crea un array 1D con 4 elementos (todos iguales a 1) # Pasa una tupla de dimensiones (2,3,4) = 2 bloques, c/u 3 filas y 4 columnas = array 3D

(array([1., 1., 1., 1.]),
 array([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],
 
        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]))

In [23]:
# Array equivalente a la matriz identidad → Diagonal = 1, fuera = 0 # Tiene que ser una matriz cuadrad
np.eye(5) # Matriz 5x5, donde diagonal = 1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
# Ejercicio: Crear un array 4x4 cuyos elementos en la diagonal sean iguales a 8, fuera de la diagonal iguales a -10
np.eye(4)*8 # Matriz 4x4, donde diagonal = 8

array([[8., 0., 0., 0.],
       [0., 8., 0., 0.],
       [0., 0., 8., 0.],
       [0., 0., 0., 8.]])

In [37]:
funcionej = -10 * np.ones((4, 4)) + 18 * np.eye(4)
# np.ones((4, 4)) → matriz 4×4 de unos.
# np.eye(4) → matriz identidad 4×4.
# -10 * np.ones(...) + 18 * np.eye(...) → da la matriz con diagonal 8 y fuera de diagonal -10.
funcionej

array([[  8., -10., -10., -10.],
       [-10.,   8., -10., -10.],
       [-10., -10.,   8., -10.],
       [-10., -10., -10.,   8.]])

In [36]:
funcionej/2

array([[ 4., -5., -5., -5.],
       [-5.,  4., -5., -5.],
       [-5., -5.,  4., -5.],
       [-5., -5., -5.,  4.]])

In [38]:
funcionej**2

array([[ 64., 100., 100., 100.],
       [100.,  64., 100., 100.],
       [100., 100.,  64., 100.],
       [100., 100., 100.,  64.]])

In [39]:
# En Python, sí está definida la división entre matrices
1/funcionej

array([[ 0.125, -0.1  , -0.1  , -0.1  ],
       [-0.1  ,  0.125, -0.1  , -0.1  ],
       [-0.1  , -0.1  ,  0.125, -0.1  ],
       [-0.1  , -0.1  , -0.1  ,  0.125]])