# TAREA

## parea el 2do parcial


Cada ejercicio está representado por una función con su docstring que contiene
la instrucción (no incluye soluciones). Implementa las funciones por tu cuenta.



In [47]:
import pandas as pd
import numpy as np

In [56]:
def ex1_concat_same_structure():
    """Ejercicio 1:
    Crea dos DataFrame que compartan la misma estructura de columnas (por ejemplo,
    'Nombre' y 'Edad'), con al menos 3 filas cada uno. Concaténalos verticalmente
    en un único DataFrame. Retorna el DataFrame resultante.
    """
    df1= pd.DataFrame({"Nombre":["chana","juana","marta"],
                      "Edad":[53,60,26]})
    df2=pd.DataFrame({"Nombre":["Lucy","Montse","Rodri"],
                     "Edad":[14,13,18]})
    return pd.concat([df1,df2], ignore_index=True)


In [57]:
def ex2_concat_with_month_column():
    """Ejercicio 2:
    Tienes un DataFrame con ventas de enero y otro con ventas de febrero (mismas columnas).
    Concaténalos en un solo DataFrame y añade una columna que indique el mes original
    de cada fila (por ejemplo: 'Enero' o 'Febrero'). Retorna el DataFrame resultante.
    """
    enero = pd.DataFrame({'Venta': [200, 150, 300], 'Producto': ['A', 'B', 'C']})
    febrero = pd.DataFrame({'Venta': [250, 100, 350], 'Producto': ['A', 'B', 'C']})
    enero['Mes'] = 'Enero'
    febrero['Mes'] = 'Febrero'
    return pd.concat([enero, febrero], ignore_index=True)


In [58]:
def ex3_concat_diff_columns_fillna():
    """Ejercicio 3:
    Crea dos DataFrame que no tengan exactamente las mismas columnas (ej.: uno tiene
    'Producto' y 'Ventas', el otro 'Producto' y 'Descuento'). Concaténalos y asegura
    que los valores faltantes queden rellenados con 0. Retorna el DataFrame resultante.
    """
    df1 = pd.DataFrame({'Producto': ['A', 'B'], 'Ventas': [100, 150]})
    df2 = pd.DataFrame({'Producto': ['C', 'D'], 'Descuento': [5, 10]})
    result = pd.concat([df1, df2], ignore_index=True).fillna(0)
    return result


In [59]:
def ex4_concat_three_groups():
    """Ejercicio 4:
    Genera tres DataFrame pequeños (cada uno con, por ejemplo, 3 filas) que representen
    notas de distintos grupos de alumnos. Concaténalos verticalmente en un solo DataFrame
    que contenga todas las notas. Retorna el DataFrame resultante.
    """
    g1 = pd.DataFrame({'Alumno': ['A1', 'A2', 'A3'], 'Nota': [8, 7, 9]})
    g2 = pd.DataFrame({'Alumno': ['B1', 'B2', 'B3'], 'Nota': [6, 9, 7]})
    g3 = pd.DataFrame({'Alumno': ['C1', 'C2', 'C3'], 'Nota': [10, 8, 9]})
    return pd.concat([g1, g2, g3], ignore_index=True)


In [60]:
def ex5_remove_duplicates_preserve_order(lst):
    """Ejercicio 5:
    Dada una lista de enteros (o strings) que puede contener duplicados, devuelve una
    nueva lista sin duplicados preservando el orden original. No uses directamente set()
    para eliminar duplicados (escribe la lógica que preserve el orden). Retorna la nueva 
    lista sin duplicados."""
    
def ex5_remove_duplicates_preserve_order(lst):
    result = []
    for i in lst:
        if i not in result:
            result.append(i)
    return result
mi_lista = [1, 2, 2, 3, 1, 4]
print(ex5_remove_duplicates_preserve_order(mi_lista))


[1, 2, 3, 4]


In [61]:
def ex6_sort_tuples_by_second_element(tuples_list):
    """Ejercicio 6:
    Dada una lista de tuplas, por ejemplo [("a", 3), ("b", 1), ("c", 2)], ordénala
    por el segundo elemento de cada tupla y devuelve la lista ordenada. Usa una función
    anónima si lo deseas. Retorna la lista ordenada.
    """
    return sorted(tuples_list, key=lambda x: x[1])
print(ex6_sort_tuples_by_second_element([("a", 3), ("b", 1), ("c", 2)]))


[('b', 1), ('c', 2), ('a', 3)]


In [62]:
def ex7_first_n_multiples_of_7(n):
    return [7 * i for i in range(1, n + 1)]
    """Ejercicio 7:
    Devuelve una lista con los primeros n múltiplos de 7 (por ejemplo, n=5 -> [7,14,21,28,35]).
    Retorna la lista generada.
    """

In [63]:
def ex8_filter_palindromes(strings):
    return [s for s in strings if s == s[::-1]]
print(ex8_filter_palindromes(["oso", "casa", "ana", "reconocer"]))

['oso', 'ana', 'reconocer']


In [64]:
def ex9_set_intersection_and_difference(set_a, set_b):
    return (set_a & set_b, set_a - set_b)
    """Ejercicio 9:
    Dado dos conjuntos, devuelve su intersección y la diferencia (elementos de A que no
    están en B). Retorna una tupla (intersección, diferencia).
    """


In [65]:
def ex10_is_subset(set_a, set_b):
    return set_a.issubset(set_b)
    """Ejercicio 10:
    Verifica si set_a es subconjunto de set_b. Devuelve True o False.
    """


In [66]:
def ex11_count_unique_elements(lst):
    return len(set(lst))
    """Ejercicio 11:
    Dada una lista, cuenta cuántos elementos únicos contiene (usa set para obtener el conteo).
    Retorna el número de elementos únicos.
    """


In [67]:

def ex12_unique_words_from_phrases(phrases):
    words = set()
    for p in phrases:
        for w in p.split():
            words.add(w)
    return words

frases = ["juan perez", "profe fer", "perez profe"]
print("Ejercicio 12:", ex12_unique_words_from_phrases(frases))

Ejercicio 12: {'juan', 'profe', 'perez', 'fer'}


In [68]:
def ex13_oldest_person(tuple_list):
    """Ejercicio 13:
    Recibe una lista de tuplas (nombre, edad). Devuelve la tupla de la persona con mayor edad.
    """
    return max(tuple_list, key=lambda x: x[1])

personas = [("pancha", 22), ("rorigo", 31), ("maya", 27)]
print("Ejercicio 13:", ex13_oldest_person(personas))

Ejercicio 13: ('rorigo', 31)


In [69]:
def ex14_convert_list_of_lists_to_tuples(list_of_lists):
    return [tuple(sublista) for sublista in list_of_lists]

listas = [[1, 2], [3, 4], [5, 6]]
print( ex14_convert_list_of_lists_to_tuples(listas))
    

[(1, 2), (3, 4), (5, 6)]


In [70]:
def ex15_sum_of_tuple_abc(t):
    """Ejercicio 15:
    Recibe una tupla de tres números (a, b, c). Desempaquétala y devuelve la suma a+b+c.
    """
    a, b, c = t
    return a + b + c

tupla = (3, 5, 2)
print( ex15_sum_of_tuple_abc(tupla))

10


In [71]:
def ex16_sort_product_price(prod_price_list):
    """Ejercicio 16:
    Dada una lista de tuplas (producto, precio), ordénala por precio de menor a mayor.
    Retorna la lista ordenada.
    """
    return sorted(prod_price_list, key=lambda x: x[1])
productos = [("Manzana", 12), ("Banana", 5), ("Pera", 9)]
print( ex16_sort_product_price(productos))

[('Banana', 5), ('Pera', 9), ('Manzana', 12)]


In [72]:
def ex17_char_frequency(s):
    """Ejercicio 17:
    Cuenta la frecuencia de cada carácter en una cadena usando un diccionario.
    Retorna un diccionario {carácter: frecuencia}.
    """
    freq = {}
    for ch in s:
        freq[ch] = freq.get(ch, 0) + 1
    return freq

texto = "banana"
print("Ejercicio 17:", ex17_char_frequency(texto))

Ejercicio 17: {'b': 1, 'a': 3, 'n': 2}


In [73]:
def ex18_best_student(grades_dict):
    """Ejercicio 18:
    Dado un diccionario {alumno: calificación}, devuelve al mejor estudiante.
    Retorna una tupla (nombre, calificación).
    """
    return max(grades_dict.items(), key=lambda x: x[1])

calificaciones = {"laura": 8.7, "jack": 9.5, "karen": 9.2}
print( ex18_best_student(calificaciones))

('jack', 9.5)


In [74]:
def ex19_invert_dictionary(d):
    """Ejercicio 19:
    Invierte un diccionario, intercambiando claves y valores.
    Retorna el diccionario invertido.
    """
    return {v: k for k, v in d.items()}

dic = {"a": 1, "b": 2, "c": 3}
print( ex19_invert_dictionary(dic))

{1: 'a', 2: 'b', 3: 'c'}


In [75]:
def ex20_merge_dicts_sum_values(d1, d2):
    """Ejercicio 20:
    Fusiona dos diccionarios sumando los valores de las claves que se repitan.
    Devuelve el diccionario resultante.
    """
    merged = d1.copy()
    for k, v in d2.items():
        merged[k] = merged.get(k, 0) + v
    return merged

d1 = {"a": 3, "b": 5}
d2 = {"b": 2, "c": 4}
print( ex20_merge_dicts_sum_values(d1, d2))

{'a': 3, 'b': 7, 'c': 4}


In [76]:
def ex21_numpy_array_set_fifth():
    """Ejercicio 21:
    Crea un arreglo de NumPy de 10 ceros y cambia el quinto elemento (índice 4) a 1.
    """
    arr = np.zeros(10, dtype=int)
    arr[4] = 1
    return arr

print( ex21_numpy_array_set_fifth())

[0 0 0 0 1 0 0 0 0 0]


In [77]:
def ex22_numpy_matrix_3x3():
    """Ejercicio 22:
    Genera una matriz 3x3 con los valores del 0 al 8.
    """
    return np.arange(9).reshape(3, 3)

print(ex22_numpy_matrix_3x3())


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [78]:
def ex23_numpy_statistics():
    """Ejercicio 23:
    Genera un array aleatorio de 20 enteros y calcula la media, mediana y desviación estándar.
    """
    arr = np.random.randint(0, 100, 20)
    mean = np.mean(arr)
    median = np.median(arr)
    std = np.std(arr)
    return mean, median, std

print(ex23_numpy_statistics())

(np.float64(34.25), np.float64(34.5), np.float64(22.183045327456732))


In [79]:
def ex24_numpy_clip_values(arr):
    """Ejercicio 24:
    Dado un array (o lista) de números, reemplaza todos los valores mayores que 10 por 10.
    """
    arr = np.array(arr)
    return np.clip(arr, None, 10)

print(ex24_numpy_clip_values([5, 11, 3, 15]))

[ 5 10  3 10]


In [80]:
def ex25_filter_rows_age_over_30():
    """Ejercicio 25:
    Crea un DataFrame con columnas 'Nombre', 'Edad' y 'Ciudad'.
    Filtra y retorna solo las filas con Edad > 30.
    """
    data = {
        "Nombre": ["Ana", "Luis", "María", "Pedro"],
        "Edad": [25, 42, 37, 19],
        "Ciudad": ["CDMX", "Querétaro", "Monterrey", "Toluca"]
    }
    df = pd.DataFrame(data)
    return df[df["Edad"] > 30]

print(ex25_filter_rows_age_over_30())

  Nombre  Edad     Ciudad
1   Luis    42  Querétaro
2  María    37  Monterrey


In [81]:
def ex26_load_dict_into_dataframe_and_sort():
    """Ejercicio 26:
    Carga un diccionario en un DataFrame y ordénalo por la columna de puntaje de mayor a menor.
    """
    data = {"Nombre": ["Ana", "Luis", "María"], "Puntaje": [80, 95, 88]}
    df = pd.DataFrame(data)
    return df.sort_values("Puntaje", ascending=False)

print(ex26_load_dict_into_dataframe_and_sort())


  Nombre  Puntaje
1   Luis       95
2  María       88
0    Ana       80


In [82]:
def ex27_groupby_mean_value():
    """Ejercicio 27:
    Dado un DataFrame con columnas 'Grupo' y 'Valor', calcula el promedio de 'Valor' por grupo.
    """
    data = {
        "Grupo": ["A", "A", "B", "B", "C"],
        "Valor": [10, 20, 30, 40, 50]
    }
    df = pd.DataFrame(data)
    return df.groupby("Grupo", as_index=False)["Valor"].mean()

print(ex27_groupby_mean_value())

  Grupo  Valor
0     A   15.0
1     B   35.0
2     C   50.0


In [83]:
def ex28_most_sold_product_from_sales_df():
    """Ejercicio 28:
    Determina el producto más vendido según la suma total de la columna 'Cantidad'.
    """
    data = {
        "Producto": ["Manzana", "Pera", "Manzana", "Plátano", "Pera"],
        "Cantidad": [5, 7, 3, 10, 2]
    }
    df = pd.DataFrame(data)
    total = df.groupby("Producto")["Cantidad"].sum()
    producto = total.idxmax()
    return producto, total[producto]

print(ex28_most_sold_product_from_sales_df())

('Plátano', np.int64(10))


In [84]:
def ex29_map_lambda_cube(lst):
    """Ejercicio 29:
    Usa map junto con una lambda para elevar al cubo cada número en una lista.
    """
    return list(map(lambda x: x**3, lst))

print(ex29_map_lambda_cube([1, 2, 3]))

[1, 8, 27]


In [85]:
def ex30_filter_lambda_even(lst):
    """Ejercicio 30:
    Usa filter y una lambda para quedarte sólo con los números pares de una lista.
    """
    return list(filter(lambda x: x % 2 == 0, lst))
    print(ex30_filter_lambda_even([1, 2, 3, 4, 5, 6]))

In [86]:
def ex31_sort_list_of_dicts_by_key(lst, keyname):
    """Ejercicio 31:
    Dada una lista de diccionarios, ordénala por el valor asociado a 'keyname'.
    """
    return sorted(lst, key=lambda x: x[keyname])

# Ejemplo
datos = [
    {"nombre": "rana", "edad": 25},
    {"nombre": "fer", "edad": 19},
    {"nombre": "moco", "edad": 30}
]
print(ex31_sort_list_of_dicts_by_key(datos, "edad"))

[{'nombre': 'fer', 'edad': 19}, {'nombre': 'rana', 'edad': 25}, {'nombre': 'moco', 'edad': 30}]


In [87]:
def ex32_pandas_apply_lambda_uppercase(names_list):
    """Ejercicio 32:
    Crea un DataFrame con una columna 'Nombre' y usa apply + lambda para crear una nueva columna con los nombres en mayúsculas.
    """
    df = pd.DataFrame({"Nombre": names_list})
    df["Mayuscula"] = df["Nombre"].apply(lambda x: x.upper())
    return df

print(ex32_pandas_apply_lambda_uppercase(["ana", "luis", "maría"]))

  Nombre Mayuscula
0    ana       ANA
1   luis      LUIS
2  maría     MARÍA
