# Examen parcial 1 - Sofia Macarena Castillo Badilla

🔹 Ejercicio Frecuencia de números en matriz

Genera una matriz 6x6 de enteros aleatorios entre 1 y 10 usando NumPy. 

Recorre la matriz y guarda en un diccionario la frecuencia de cada número.

Convierte el diccionario en una lista de tuplas (número, frecuencia) y ordénala de mayor a menor frecuencia.

Imprime la matriz, el diccionario y la lista ordenada.

In [1]:
import numpy as np

In [23]:
# 1.
matriz = np.random.randint(1,11, size = [6,6])
matriz

array([[ 3,  8,  7,  5,  6,  8],
       [ 9,  5,  1,  8,  4,  7],
       [ 3,  9,  8,  7,  1,  2],
       [ 1,  6,  7, 10,  6,  3],
       [ 2,  2,  8,  1,  3,  5],
       [ 2, 10,  7,  4,  6,  2]])

In [58]:
# 2.
diccionario_matriz = {}

valor, conteo = np.unique(matriz, return_counts=True) # En numpy count() no funciona.

diccionario_matriz = {i: 0 for i in range(1, 11)} 
for v, c in zip(valor, conteo):
    diccionario_matriz[v] = c
            
print(diccionario_matriz)

        

{1: np.int64(4), 2: np.int64(5), 3: np.int64(4), 4: np.int64(2), 5: np.int64(3), 6: np.int64(4), 7: np.int64(5), 8: np.int64(5), 9: np.int64(2), 10: np.int64(2)}


In [73]:
# 3. 
tupla_matriz = list(diccionario_matriz.items())
tupla_matriz_ordenada = sorted(tupla_matriz, key=lambda x: x[1], reverse=True)
tupla_matriz_ordenada

[(2, np.int64(5)),
 (7, np.int64(5)),
 (8, np.int64(5)),
 (1, np.int64(4)),
 (3, np.int64(4)),
 (6, np.int64(4)),
 (5, np.int64(3)),
 (4, np.int64(2)),
 (9, np.int64(2)),
 (10, np.int64(2))]

In [74]:
# 4.
matriz, diccionario_matriz, tupla_matriz_ordenada

(array([[ 3,  8,  7,  5,  6,  8],
        [ 9,  5,  1,  8,  4,  7],
        [ 3,  9,  8,  7,  1,  2],
        [ 1,  6,  7, 10,  6,  3],
        [ 2,  2,  8,  1,  3,  5],
        [ 2, 10,  7,  4,  6,  2]]),
 {1: np.int64(4),
  2: np.int64(5),
  3: np.int64(4),
  4: np.int64(2),
  5: np.int64(3),
  6: np.int64(4),
  7: np.int64(5),
  8: np.int64(5),
  9: np.int64(2),
  10: np.int64(2)},
 [(2, np.int64(5)),
  (7, np.int64(5)),
  (8, np.int64(5)),
  (1, np.int64(4)),
  (3, np.int64(4)),
  (6, np.int64(4)),
  (5, np.int64(3)),
  (4, np.int64(2)),
  (9, np.int64(2)),
  (10, np.int64(2))])

## 🔹 Ejercicio Promedios por columna y gráfico de líneas

Crea una matriz 10x5 con enteros entre 10 y 100.

Calcula el promedio de cada columna usando un bucle.

Guarda los resultados en un diccionario con claves "col_1" ... "col_5".

Convierte los valores en una lista y grafícalos en una línea (line plot) mostrando el promedio por columna.

In [77]:
#1. 
matriz_10x5 = np.random.randint(10, 101, size = [10, 5])
matriz_10x5

array([[41, 81, 41, 83, 44],
       [74, 62, 22, 26, 33],
       [43, 30, 34, 43, 52],
       [64, 24, 88, 70, 63],
       [87, 35, 74, 80, 73],
       [68, 72, 37, 86, 89],
       [79, 58, 47, 83, 34],
       [96, 58, 10, 97, 41],
       [91, 10, 52, 89, 34],
       [68, 39, 37, 36, 73]])

In [ ]:
#2. 
for columna 

🔹 Ejercicio Evolución temporal simulada

Simula con NumPy una lista de 30 días con valores aleatorios de temperatura entre 15°C y 35°C.

Almacena los valores en un diccionario con claves "día_1", "día_2", ....

Usa un bucle para crear una lista con los días donde la temperatura superó 30°C.

Grafica las temperaturas en un gráfico de línea con puntos marcados (scatter + line plot).

Marca en rojo los días con temperatura > 30°C.

🔹 Ejercicio Comparación de distribuciones

Genera dos arreglos de 100 números aleatorios con distribución normal:

grupo_A: media 50, desviación 10

grupo_B: media 60, desviación 15

Guarda en un diccionario con claves "A" y "B".

Calcula media y desviación estándar de cada grupo y guárdalas en listas.

Grafica ambos grupos en un histograma comparativo (superposición con colores diferentes y transparencia).

🔹 Ejercicio Clasificación de temperaturas

Genera una Serie con 50 valores aleatorios entre -10 y 40 (temperaturas).

Recorre la Serie y clasifica cada temperatura en un diccionario:

"frío" si < 10

"templado" si 10–25

"calor" si > 25

Convierte el diccionario en un DataFrame con columnas "Temperatura" y "Categoría".

Cuenta cuántos valores cayeron en cada categoría.

🔹 Ejercicio Matriz de distancias

Genera una matriz 10x2 con coordenadas aleatorias (x, y) entre 0 y 100.

Con un bucle, calcula las distancias euclidianas entre cada par de puntos y guárdalas en un diccionario con claves (i,j).

Convierte el diccionario en un DataFrame de 10x10 (matriz de distancias).

Encuentra el par de puntos más cercanos y el más lejano.

🔹 Ejercicio Análisis de series temporales

Genera con NumPy una Serie de 365 valores aleatorios entre 10 y 40 (temperatura diaria de un año).

Convierte en un DataFrame con columnas "Día" y "Temperatura".

Usa un bucle para calcular la media de cada mes (asume 30 días por mes).

Guarda las medias en un diccionario {Mes: Promedio}.

Convierte el diccionario en una Series y ordénala de mayor a menor.

🔹 Ejercicio Actividad neuronal por regiones

Genera una matriz 100x5 con NumPy representando la actividad de 100 neuronas en 5 regiones cerebrales (valores entre 0 y 1 como tasas de disparo).

Convierte la matriz en un DataFrame con columnas "Región_1"... "Región_5".

Usa un bucle para calcular la actividad media de cada región y guárdala en un diccionario.

Convierte el diccionario en una Series y ordénala de mayor a menor.

🔹 Ejercicio Conectividad funcional (correlaciones)

Simula con NumPy una matriz 200x4 con series de tiempo de actividad fMRI en 4 áreas cerebrales.

Convierte en un DataFrame con columnas "Área_1"... "Área_4".

Con un bucle, calcula la correlación de Pearson entre todas las parejas de áreas y guárdala en un diccionario con claves (Área_i, Área_j).

Convierte el diccionario en un DataFrame cuadrado (matriz de conectividad).

🔹 Ejercicio Potenciales de acción por neurona

Genera una lista de 50 neuronas.

Para cada neurona, simula con NumPy una Serie de 100 ms de actividad (valores enteros 0 o 1 indicando si disparó o no).

Guarda los resultados en un diccionario {Neurona: Serie}.

Crea un DataFrame con todas las neuronas (filas) y tiempos (columnas).

Usa un bucle para contar cuántos disparos totales tuvo cada neurona y genera una Series con esos valores.

🔹 Ejercicio EEG por canales

Simula una matriz 500x8 con NumPy representando 500 muestras de señal EEG en 8 canales (valores flotantes entre -100 y 100 µV).

Convierte la matriz en un DataFrame con columnas "Canal_1"... "Canal_8".

Usa un bucle para calcular la potencia media de cada canal (media del cuadrado de la señal).

Guarda los resultados en un diccionario y conviértelo en una Series ordenada.

Identifica el canal con mayor potencia.

🔹 Ejercicio Análisis de respuestas a estímulos

Genera un DataFrame con 30 sujetos (filas) y 3 condiciones experimentales ("Cond_A", "Cond_B", "Cond_C") con valores de tiempo de reacción simulados (valores entre 200–800 ms).

Usa un bucle para calcular el promedio por condición en toda la muestra.

Convierte los resultados en un diccionario y luego en una Series.

Agrega una columna "Mejor_condición" al DataFrame indicando la condición más rápida por sujeto.

Cuenta cuántos sujetos respondieron mejor en cada condición.