üîπ Ejercicio Frecuencia de n√∫meros en matriz

Genera una matriz 6x6 de enteros aleatorios entre 1 y 10 usando NumPy.

Recorre la matriz y guarda en un diccionario la frecuencia de cada n√∫mero.

Convierte el diccionario en una lista de tuplas (número, frecuencia) y ordénala de mayor a menor frecuencia.

Imprime la matriz, el diccionario y la lista ordenada.

In [22]:
import numpy as np

#Generar la matriz
rng = np.random.default_rng(seed=123)
matriz = rng.integers(1, 11, size=(6, 6))

#Calcular frecuencias con bucle 
frecuencias = {}
for fila in matriz:
    for num in fila:
        if num in frecuencias:
            frecuencias[num] += 1
        else:
            frecuencias[num] = 1

#Convertir a lista de tuplas y ordenar 
lista_ordenada = sorted(frecuencias.items(), key=lambda x: x[1], reverse=True)

# Impresiones 
print("=== Matriz generada ===")
print(matriz)
print()
print("=== Diccionario de frecuencias ===")
print(frecuencias)
print()
print("=== Lista ordenada (n√∫mero, frecuencia) ===")
print(lista_ordenada)

=== Matriz generada ===
[[ 1  7  6  1 10  3]
 [ 3  2  4  2  4  9]
 [ 5 10  5  3  8  9]
 [ 9  9  1  6  3  3]
 [ 3  9  8  3  5  8]
 [ 2  7  5 10  8  3]]

=== Diccionario de frecuencias ===
{np.int64(1): 3, np.int64(7): 2, np.int64(6): 2, np.int64(10): 3, np.int64(3): 8, np.int64(2): 3, np.int64(4): 2, np.int64(9): 5, np.int64(5): 4, np.int64(8): 4}

=== Lista ordenada (n√∫mero, frecuencia) ===
[(np.int64(3), 8), (np.int64(9), 5), (np.int64(5), 4), (np.int64(8), 4), (np.int64(1), 3), (np.int64(10), 3), (np.int64(2), 3), (np.int64(7), 2), (np.int64(6), 2), (np.int64(4), 2)]


🔹 Ejercicio Promedios por columna y gráfico de líneas

Crea una matriz 10x5 con enteros entre 10 y 100.

Calcula el promedio de cada columna usando un bucle.

Guarda los resultados en un diccionario con claves "col_1" ... "col_5".

Convierte los valores en una lista y grafícalos en una línea (line plot) mostrando el promedio por columna.

In [23]:
import numpy as np
import matplotlib.pyplot as plt

# Configuración
rng = np.random.default_rng(seed=42)
matriz = rng.integers(10, 101, size=(10, 5))  # 10x5 con enteros entre 10 y 100

# Calcular promedios por columna con bucle 
promedios = {}
for j in range(matriz.shape[1]):
    prom = matriz[:, j].mean()
    promedios[f"col_{j+1}"] = prom

# Convertir a lista de valores 
valores = list(promedios.values())

# Impresiones 
print("=== Matriz generada ===")
print(matriz)
print()
print("=== Promedios por columna ===")
for col, val in promedios.items():
    print(f"{col:<6}: {val:.2f}")
print()

#Gráfico de líneas
plt.plot(range(1, len(valores)+1), valores, marker="o", linestyle="-", color="blue")
plt.xticks(range(1, len(valores)+1), list(promedios.keys()))
plt.xlabel("Columnas")
plt.ylabel("Promedio")
plt.title("Promedio por columna")
plt.grid(True, linestyle="--", alpha=0.6)
plt.show()

=== Matriz generada ===
[[18 80 69 49 49]
 [88 17 73 28 18]
 [57 98 76 79 75]
 [81 56 21 86 50]
 [55 43 26 94 81]
 [68 46 84 59 50]
 [50 30 18 60 90]
 [15 88 85 35 67]
 [25 78 73 42 16]
 [98 50 91 71 80]]

=== Promedios por columna ===
col_1 : 55.50
col_2 : 58.60
col_3 : 61.60
col_4 : 60.30
col_5 : 57.60



🔹 Ejercicio Evolución temporal simulada

Simula con NumPy una lista de 30 días con valores aleatorios de temperatura entre 15°C y 35°C.

Almacena los valores en un diccionario con claves "día_1", "día_2", ....

Usa un bucle para crear una lista con los días donde la temperatura superó 30°C.

Grafica las temperaturas en un gráfico de línea con puntos marcados (scatter + line plot).

Marca en rojo los días con temperatura > 30°C.

In [25]:
import numpy as np
import matplotlib.pyplot as plt

#Lista
rng = np.random.default_rng(seed=7)
n_dias = 30

#Simulación de temperaturas
temps = rng.uniform(15, 35, size=n_dias)

# Diccionario {día_i: temperatura}
datos = {f"día_{i+1}": round(temps[i], 2) for i in range(n_dias)}

#Días con temperatura > 30°C 
dias_calor = []
for i, t in enumerate(temps, start=1):
    if t > 30:
        dias_calor.append(i)

# Impresiones 
print("=== Vista previa de temperaturas (primeros 10 días) ===")
for k in list(datos.keys())[:10]:
    print(f"{k:<8}: {datos[k]} °C")
print()
print("Días con temperatura > 30°C:", dias_calor)
print()

#Gráfico de línea + puntos 
plt.plot(range(1, n_dias+1), temps, marker="o", color="black", label="Temperatura")
plt.scatter(dias_calor, temps[np.array(dias_calor)-1], color="red", label=">30°C", zorder=5)
plt.xlabel("Día")
plt.ylabel("Temperatura (°C)")
plt.title("Evolución temporal de la temperatura (30 días)")
plt.legend()
plt.show()

=== Vista previa de temperaturas (primeros 10 días) ===
día_1   : 27.5 °C
día_2   : 32.94 °C
día_3   : 30.51 °C
día_4   : 19.5 °C
día_5   : 21.0 °C
día_6   : 32.47 °C
día_7   : 15.11 °C
día_8   : 31.42 °C
día_9   : 30.94 °C
día_10  : 24.36 °C

Días con temperatura > 30°C: [2, 3, 6, 8, 9, 17, 18, 20, 28]



🔹 Ejercicio Comparación de distribuciones

Genera dos arreglos de 100 números aleatorios con distribución normal:

grupo_A: media 50, desviación 10

grupo_B: media 60, desviación 15

Guarda en un diccionario con claves "A" y "B".

Calcula media y desviación estándar de cada grupo y guárdalas en listas.

Grafica ambos grupos en un histograma comparativo (superposición con colores diferentes y transparencia).

In [27]:
import numpy as np
import matplotlib.pyplot as plt

rng = np.random.default_rng(seed=2025)
n = 100

#Generar datos 
grupo_A = rng.normal(loc=50, scale=10, size=n)
grupo_B = rng.normal(loc=60, scale=15, size=n)

datos = {"A": grupo_A, "B": grupo_B}

#Calcular estadísticas 
medias = [np.mean(grupo_A), np.mean(grupo_B)]
desvs = [np.std(grupo_A, ddof=1), np.std(grupo_B, ddof=1)]

#Impresiones bonitas 
print("=== Estadísticas por grupo ===")
print(f"{'Grupo':<8}{'Media':>10}{'Desv.Std':>12}")
print("-" * 30)
for nombre, media, desv in zip(["A", "B"], medias, desvs):
    print(f"{nombre:<8}{media:>10.2f}{desv:>12.2f}")
print()

#Histograma comparativo 
plt.hist(grupo_A, bins=15, alpha=0.6, label="Grupo A", color="blue")
plt.hist(grupo_B, bins=15, alpha=0.6, label="Grupo B", color="green")
plt.xlabel("Valor")
plt.ylabel("Frecuencia")
plt.title("Comparación de distribuciones (A vs B)")
plt.legend()
plt.show()

=== Estadísticas por grupo ===
Grupo        Media    Desv.Std
------------------------------
A            49.64       11.50
B            59.52       16.24



🔹 Ejercicio Clasificación de temperaturas

Genera una Serie con 50 valores aleatorios entre -10 y 40 (temperaturas).

Recorre la Serie y clasifica cada temperatura en un diccionario:

"frío" si < 10

"templado" si 10–25

"calor" si > 25

Convierte el diccionario en un DataFrame con columnas "Temperatura" y "Categoría".

Cuenta cuántos valores cayeron en cada categoría.

In [28]:
import numpy as np

# Serie
rng = np.random.default_rng(seed=99)
n = 50
temperaturas = rng.uniform(-10, 40, size=n)

#Clasificación manual 
clasificacion = {}
for i, temp in enumerate(temperaturas):
    if temp < 10:
        categoria = "frío"
    elif temp <= 25:
        categoria = "templado"
    else:
        categoria = "calor"
    clasificacion[i] = (round(temp, 2), categoria)

#Conteo por categoría 
conteo = {"frío": 0, "templado": 0, "calor": 0}
for _, (_, cat) in clasificacion.items():
    conteo[cat] += 1

#Impresiones bonitas 
print("=== Vista previa de temperaturas clasificadas (primeros 10) ===")
print(f"{'Índice':<8}{'Temperatura':>12}{'Categoría':>12}")
print("-" * 32)
for i in range(10):
    temp, cat = clasificacion[i]
    print(f"{i:<8}{temp:>12.2f}{cat:>12}")
print()

print("=== Conteo por categoría ===")
for cat, c in conteo.items():
    print(f"{cat:<10}: {c}")

=== Vista previa de temperaturas clasificadas (primeros 10) ===
Índice   Temperatura   Categoría
--------------------------------
0              15.30    templado
1              18.25    templado
2              15.60    templado
3              38.61       calor
4              20.75    templado
5              18.41    templado
6               4.34        frío
7              17.73    templado
8              13.38    templado
9              20.50    templado

=== Conteo por categoría ===
frío      : 19
templado  : 20
calor     : 11


üîπ Ejercicio Matriz de distancias

Genera una matriz 10x2 con coordenadas aleatorias (x, y) entre 0 y 100.

Con un bucle, calcula las distancias euclidianas entre cada par de puntos y gu√°rdalas en un diccionario con claves (i,j).

Convierte el diccionario en un DataFrame de 10x10 (matriz de distancias).

Encuentra el par de puntos m√°s cercanos y el m√°s lejano.

In [29]:
import numpy as np
rng = np.random.default_rng(seed=123)
n_puntos = 10
puntos = rng.uniform(0, 100, size=(n_puntos, 2))

#Calcular distancias euclidianas con bucle 
distancias = {}
for i in range(n_puntos):
    for j in range(n_puntos):
        dx = puntos[i, 0] - puntos[j, 0]
        dy = puntos[i, 1] - puntos[j, 1]
        d = np.sqrt(dx**2 + dy**2)
        distancias[(i, j)] = d

#Generar matriz
matriz = np.zeros((n_puntos, n_puntos))
for (i, j), d in distancias.items():
    matriz[i, j] = d

#Encontrar pares m√°s cercano y m√°s lejano (excluyendo diagonal)
distancias_validas = {(i, j): d for (i, j), d in distancias.items() if i < j}
par_cercano = min(distancias_validas, key=distancias_validas.get)
par_lejano = max(distancias_validas, key=distancias_validas.get)

#Impresiones bonitas 
print("=== Coordenadas de los puntos ===")
print(f"{'Punto':<8}{'x':>10}{'y':>10}")
print("-" * 28)
for i, (x, y) in enumerate(puntos):
    print(f"P{i:<7}{x:>10.2f}{y:>10.2f}")
print()

print("=== Matriz de distancias (redondeada) ===")
print(f"{'':<6}" + "".join([f"P{j:<6}" for j in range(n_puntos)]))
for i in range(n_puntos):
    fila = "".join([f"{matriz[i,j]:<6.1f}" for j in range(n_puntos)])
    print(f"P{i:<5}{fila}")
print()

print(f"Par m√°s cercano: P{par_cercano[0]} - P{par_cercano[1]} con distancia {distancias_validas[par_cercano]:.2f}")
print(f"Par m√°s lejano:  P{par_lejano[0]} - P{par_lejano[1]} con distancia {distancias_validas[par_lejano]:.2f}")

=== Coordenadas de los puntos ===
Punto            x         y
----------------------------
P0           68.24      5.38
P1           22.04     18.44
P2           17.59     81.21
P3           92.33     27.66
P4           81.98     88.99
P5           51.30     24.50
P6           82.42     21.38
P7           74.15     62.99
P8           92.74     23.19
P9           79.91     51.82

=== Matriz de distancias (redondeada) ===
      P0     P1     P2     P3     P4     P5     P6     P7     P8     P9     
P0    0.0   48.0  91.2  32.8  84.7  25.5  21.4  57.9  30.3  47.9  
P1    48.0  0.0   62.9  70.9  92.6  29.9  60.5  68.6  70.9  66.8  
P2    91.2  62.9  0.0   91.9  64.9  66.0  88.2  59.4  94.9  68.9  
P3    32.8  70.9  91.9  0.0   62.2  41.2  11.7  39.7  4.5   27.2  
P4    84.7  92.6  64.9  62.2  0.0   71.4  67.6  27.1  66.7  37.2  
P5    25.5  29.9  66.0  41.2  71.4  0.0   31.3  44.8  41.5  39.6  
P6    21.4  60.5  88.2  11.7  67.6  31.3  0.0   42.4  10.5  30.5  
P7    57.9  68.6  59.4  39.7 

üîπ Ejercicio An√°lisis de series temporales

Genera con NumPy una Serie de 365 valores aleatorios entre 10 y 40 (temperatura diaria de un año).

Convierte en un DataFrame con columnas "Día" y "Temperatura".

Usa un bucle para calcular la media de cada mes (asume 30 días por mes).

Guarda las medias en un diccionario {Mes: Promedio}.

Convierte el diccionario en una Series y ordénala de mayor a menor.

In [30]:
import numpy as np
rng = np.random.default_rng(seed=42)
dias = 365
temperaturas = rng.uniform(10, 40, size=dias)

# DataFrame
dias_lista = list(range(1, dias + 1))

# Calcular medias mensuales con bucle (30 días por mes)
medias = {}
for mes in range(1, 13):
    inicio = (mes - 1) * 30
    fin = mes * 30
    if inicio < dias:  # asegurar que no me paso
        datos_mes = temperaturas[inicio:fin]
        medias[f"Mes_{mes}"] = datos_mes.mean()

#Ordenar resultados
medias_ordenadas = dict(sorted(medias.items(), key=lambda x: x[1], reverse=True))

#Impresiones
print("=== Vista previa de temperaturas diarias (primeros 10 días) ===")
print(f"{'Día':<6}{'Temperatura':>12}")
print("-" * 18)
for i in range(10):
    print(f"{dias_lista[i]:<6}{temperaturas[i]:>12.2f}")
print()

print("=== Promedios mensuales (ordenados de mayor a menor) ===")
for mes, val in medias_ordenadas.items():
    print(f"{mes:<8}: {val:.2f} °C")

=== Vista previa de temperaturas diarias (primeros 10 días) ===
Día    Temperatura
------------------
1            33.22
2            23.17
3            35.76
4            30.92
5            12.83
6            39.27
7            32.83
8            33.58
9            13.84
10           23.51

=== Promedios mensuales (ordenados de mayor a menor) ===
Mes_1   : 26.77 °C
Mes_12  : 26.60 °C
Mes_6   : 26.03 °C
Mes_8   : 25.49 °C
Mes_4   : 25.31 °C
Mes_11  : 25.24 °C
Mes_2   : 24.41 °C
Mes_10  : 24.10 °C
Mes_7   : 24.05 °C
Mes_9   : 23.55 °C
Mes_3   : 23.35 °C
Mes_5   : 22.92 °C


üîπ Ejercicio Actividad neuronal por regiones

Genera una matriz 100x5 con NumPy representando la actividad de 100 neuronas en 5 regiones cerebrales (valores entre 0 y 1 como tasas de disparo).

Convierte la matriz en un DataFrame con columnas "Región_1"... "Región_5".

Usa un bucle para calcular la actividad media de cada región y guárdala en un diccionario.

Convierte el diccionario en una Series y ordénala de mayor a menor.

In [31]:
import numpy as np
rng = np.random.default_rng(seed=2025)
n_neuronas = 100
n_regiones = 5
regiones = [f"Región_{i}" for i in range(1, n_regiones + 1)]

#Simulación de actividad (tasas de disparo en [0,1]) 
matriz = rng.uniform(0, 1, size=(n_neuronas, n_regiones))

#Calcular actividad media por región con bucle 
medias = {}
for j, reg in enumerate(regiones):
    medias[reg] = matriz[:, j].mean()

#Ordenar resultados 
medias_ordenadas = dict(sorted(medias.items(), key=lambda x: x[1], reverse=True))

#Impresiones bonitas 
print("=== Vista previa de la actividad (primeros 5 sujetos) ===")
print(f"{'Sujeto':<10}" + "".join([f"{r:>12}" for r in regiones]))
print("-" * (12 * (n_regiones + 1)))
for i in range(5):
    fila = "".join([f"{v:>12.3f}" for v in matriz[i]])
    print(f"{i+1:<10}{fila}")
print()

print("=== Actividad media por región (ordenada) ===")
for reg, val in medias_ordenadas.items():
    print(f"{reg:<10}: {val:.3f}")

=== Vista previa de la actividad (primeros 5 sujetos) ===
Sujeto        Región_1    Región_2    Región_3    Región_4    Región_5
------------------------------------------------------------------------
1                0.994       0.382       0.827       0.837       0.976
2                0.077       0.317       0.920       0.676       0.286
3                0.390       0.230       0.167       0.153       0.974
4                0.424       0.063       0.492       0.288       0.212
5                0.207       0.579       0.591       0.888       0.110

=== Actividad media por región (ordenada) ===
Región_4  : 0.565
Región_5  : 0.540
Región_3  : 0.521
Región_2  : 0.492
Región_1  : 0.466


üîπ Ejercicio Conectividad funcional (correlaciones)

Simula con NumPy una matriz 200x4 con series de tiempo de actividad fMRI en 4 √°reas cerebrales.

Convierte en un DataFrame con columnas "Área_1"... "Área_4".

Con un bucle, calcula la correlación de Pearson entre todas las parejas de áreas y guárdala en un diccionario con claves (Área_i, Área_j).

Convierte el diccionario en un DataFrame cuadrado (matriz de conectividad).

In [32]:
import numpy as np
rng = np.random.default_rng(seed=7)
n_muestras = 200
n_areas = 4
areas = [f"Área_{i}" for i in range(1, n_areas + 1)]

# Simulación de series fMRI 
# Mezcla de componente común + ruido para que haya correlación
comun = rng.normal(0, 1, size=(n_muestras, 1))
ruido = rng.normal(0, 1, size=(n_muestras, n_areas))
series = 0.5 * comun + 0.5 * ruido

# Calcular correlaciones de Pearson con bucle 
correlaciones = {}
for i in range(n_areas):
    for j in range(n_areas):
        if i == j:
            correlaciones[(areas[i], areas[j])] = 1.0
        else:
            x = series[:, i]
            y = series[:, j]
            r = np.corrcoef(x, y)[0, 1]
            correlaciones[(areas[i], areas[j])] = r

#Convertir a matriz 
matriz = np.zeros((n_areas, n_areas))
for i in range(n_areas):
    for j in range(n_areas):
        matriz[i, j] = correlaciones[(areas[i], areas[j])]

#Impresiones 
print("=== Vista previa de las series fMRI (primeras 5 filas) ===")
print(f"{'Muestra':<10}" + "".join([f"{a:>12}" for a in areas]))
print("-" * (12 * (n_areas + 1)))
for i in range(5):
    fila = "".join([f"{v:>12.2f}" for v in series[i]])
    print(f"{i+1:<10}{fila}")
print()

print("=== Matriz de conectividad (correlaciones de Pearson) ===")
print(f"{'':<10}" + "".join([f"{a:>12}" for a in areas]))
print("-" * (12 * (n_areas + 1)))
for i, ai in enumerate(areas):
    fila = "".join([f"{matriz[i,j]:>12.3f}" for j in range(n_areas)])
    print(f"{ai:<10}{fila}")

=== Vista previa de las series fMRI (primeras 5 filas) ===
Muestra         Área_1      Área_2      Área_3      Área_4
------------------------------------------------------------
1                -0.62        0.43        0.25        0.44
2                 1.09        0.89       -0.42       -0.69
3                 0.27       -0.64       -0.14        0.28
4                -1.27       -1.50       -0.32       -0.42
5                -0.35       -0.21       -0.66       -0.98

=== Matriz de conectividad (correlaciones de Pearson) ===
                Área_1      Área_2      Área_3      Área_4
------------------------------------------------------------
Área_1           1.000       0.491       0.460       0.403
Área_2           0.491       1.000       0.491       0.415
Área_3           0.460       0.491       1.000       0.409
Área_4           0.403       0.415       0.409       1.000


🔹 Ejercicio Potenciales de acción por neurona

Genera una lista de 50 neuronas.

Para cada neurona, simula con NumPy una Serie de 100 ms de actividad (valores enteros 0 o 1 indicando si disparó o no).

Guarda los resultados en un diccionario {Neurona: Serie}.

Crea un DataFrame con todas las neuronas (filas) y tiempos (columnas).

Usa un bucle para contar cu√°ntos disparos totales tuvo cada neurona y genera una Series con esos valores.

In [34]:
import numpy as np
rng = np.random.default_rng(seed=2025)
n_neuronas = 50
tiempo_ms = 100
neuronas = [f"Neurona_{i:02d}" for i in range(1, n_neuronas + 1)]

#Simulación de actividad (0 = no dispara, 1 = dispara)
prob_disparo = 0.1
actividad = {}
for neurona in neuronas:
    disparos = rng.binomial(1, prob_disparo, size=tiempo_ms)
    actividad[neurona] = disparos

#Crear matriz de datos 
matriz = np.array([actividad[n] for n in neuronas])

#Conteo de disparos totales por neurona con bucle
conteo = {}
for i, neurona in enumerate(neuronas):
    conteo[neuronas[i]] = int(matriz[i].sum())

#Impresiones 
print("=== Vista previa de actividad (primeras 5 neuronas) ===")
print(f"{'Neurona':<12}" + "".join([f"t{j+1:03d} " for j in range(10)]) + "...")
for i in range(5):
    fila = "".join([f"{v:>4}" for v in matriz[i, :10]])
    print(f"{neuronas[i]:<12}{fila} ...")
print()

print("=== Disparos totales por neurona ===")
for n, c in list(conteo.items())[:10]:
    print(f"{n:<12}: {c} disparos")
print("...")

=== Vista previa de actividad (primeras 5 neuronas) ===
Neurona     t001 t002 t003 t004 t005 t006 t007 t008 t009 t010 ...
Neurona_01     1   0   0   0   1   0   0   1   0   0 ...
Neurona_02     0   0   0   0   0   0   0   0   0   0 ...
Neurona_03     0   0   0   0   0   1   0   0   1   0 ...
Neurona_04     0   0   0   0   0   0   0   0   0   0 ...
Neurona_05     0   0   0   0   0   0   0   0   0   0 ...

=== Disparos totales por neurona ===
Neurona_01  : 17 disparos
Neurona_02  : 8 disparos
Neurona_03  : 12 disparos
Neurona_04  : 13 disparos
Neurona_05  : 11 disparos
Neurona_06  : 8 disparos
Neurona_07  : 7 disparos
Neurona_08  : 14 disparos
Neurona_09  : 6 disparos
Neurona_10  : 11 disparos
...


üîπ Ejercicio EEG por canales

Simula una matriz 500x8 con NumPy representando 500 muestras de señal EEG en 8 canales (valores flotantes entre -100 y 100 µV).

Convierte la matriz en un DataFrame con columnas "Canal_1"... "Canal_8".

Usa un bucle para calcular la potencia media de cada canal (media del cuadrado de la señal).

Guarda los resultados en un diccionario y conviértelo en una Series ordenada.

Identifica el canal con mayor potencia.

In [35]:
import numpy as np
rng = np.random.default_rng(seed=123) 
n_muestras = 500
n_canales = 8
canales = [f"Canal_{i}" for i in range(1, n_canales + 1)]

#Simulación de la señal EEG
# Valores flotantes entre -100 y 100 µV
datos = rng.uniform(-100, 100, size=(n_muestras, n_canales))

# Calcular potencia media por canal con bucle
# Potencia media = promedio(x^2)
potencias = {}
for j, canal in enumerate(canales):
    potencias[canal] = (datos[:, j]**2).mean()

#Ordenar potencias 
potencias_ordenadas = dict(sorted(potencias.items(),
                                  key=lambda x: x[1],
                                  reverse=True))

# Canal con mayor potencia
canal_max, valor_max = max(potencias.items(), key=lambda x: x[1])

#Impresiones bonitas
print("=== Vista previa de los primeros 5 registros (EEG) ===")
print(f"{'Muestra':<10}" + "".join([f"{c:>12}" for c in canales]))
print("-" * (12 * (n_canales + 1)))
for i in range(5):
    fila = "".join([f"{v:>12.2f}" for v in datos[i]])
    print(f"{i+1:<10}{fila}")
print()

print("=== Potencia media por canal (ordenada) ===")
for canal, val in potencias_ordenadas.items():
    print(f"{canal:<10}: {val:.2f} µV²")
print()

print(f"Canal con mayor potencia: {canal_max} ({valor_max:.2f} µV²)")

=== Vista previa de los primeros 5 registros (EEG) ===
Muestra        Canal_1     Canal_2     Canal_3     Canal_4     Canal_5     Canal_6     Canal_7     Canal_8
------------------------------------------------------------------------------------------------------------
1                36.47      -89.24      -55.93      -63.13      -64.82       62.42       84.67      -44.69
2                63.95       77.98        2.59      -51.01       64.85      -57.25       48.29       25.99
3                85.48      -53.62       59.83        3.63      -53.69      -66.82       -0.44       16.54
4               -63.13      -97.02       -5.77       45.65       83.72       25.11       83.42       72.94
5               -56.37       73.23       46.15      -44.43       59.41       73.04      -40.11        5.41

=== Potencia media por canal (ordenada) ===
Canal_5   : 3390.28 µV²
Canal_1   : 3368.47 µV²
Canal_3   : 3303.84 µV²
Canal_7   : 3297.15 µV²
Canal_4   : 3284.88 µV²
Canal_2   : 3208.55

🔹 Ejercicio Análisis de respuestas a estímulos

Genera un DataFrame con 30 sujetos (filas) y 3 condiciones experimentales ("Cond_A", "Cond_B", "Cond_C") con valores de tiempo de reacción simulados (valores entre 200–800 ms).

Usa un bucle para calcular el promedio por condición en toda la muestra.

Convierte los resultados en un diccionario y luego en una Series.

Agrega una columna "Mejor_condición" al DataFrame indicando la condición más rápida por sujeto.

Cuenta cuántos sujetos respondieron mejor en cada condición.

In [36]:
import numpy as np

#Configuración reproducible
rng = np.random.default_rng(seed=42)

condiciones = ["Cond_A", "Cond_B", "Cond_C"]
sujetos = [f"Sujeto_{i:02d}" for i in range(1, 31)]  # Sujeto_01 ... Sujeto_30

# Simulación de tiempos de reacción (200–800 ms)
def simular_tiempos(n):
    datos = rng.normal(loc=450, scale=90, size=n)
    return np.clip(datos, 200, 800)

datos = np.column_stack([
    simular_tiempos(len(sujetos)),
    simular_tiempos(len(sujetos)),
    simular_tiempos(len(sujetos))
]).round(2)

#Promedios por condición (con bucle) 
promedios_dict = {}
for j, cond in enumerate(condiciones):
    promedios_dict[cond] = round(datos[:, j].mean(), 2)

#Mejor condición por sujeto 
mejor_condiciones = []
for fila in datos:
    idx_min = np.argmin(fila)
    mejor_condiciones.append(condiciones[idx_min])

#Conteo de mejores condiciones 
conteo = {cond: 0 for cond in condiciones}
for mc in mejor_condiciones:
    conteo[mc] += 1

#Impresiones
print("=== Vista previa (primeros 5 sujetos) ===")
print(f"{'Sujeto':<10} {'Cond_A':>10} {'Cond_B':>10} {'Cond_C':>10} {'Mejor_condición':>18}")
print("-"*62)
for i in range(5):
    print(f"{sujetos[i]:<10} "
          f"{datos[i,0]:>10.2f} {datos[i,1]:>10.2f} {datos[i,2]:>10.2f} "
          f"{mejor_condiciones[i]:>18}")
print()

print("=== Promedio por condición ===")
for cond, val in promedios_dict.items():
    print(f"{cond:<10}: {val:.2f} ms")
print()

print("=== Conteo de 'Mejor_condición' ===")
for cond in condiciones:
    print(f"{cond:<10}: {conteo[cond]} sujetos")
print()

print("=== Porcentaje de sujetos con mejor respuesta ===")
for cond in condiciones:
    porcentaje = conteo[cond] / len(sujetos) * 100
    print(f"{cond:<10}: {porcentaje:.1f}%")

=== Vista previa (primeros 5 sujetos) ===
Sujeto         Cond_A     Cond_B     Cond_C    Mejor_condición
--------------------------------------------------------------
Sujeto_01      477.42     642.75     298.54             Cond_C
Sujeto_02      356.40     413.42     419.86             Cond_A
Sujeto_03      517.54     403.90     464.65             Cond_B
Sujeto_04      534.65     376.76     502.76             Cond_B
Sujeto_05      274.41     505.44     514.01             Cond_A

=== Promedio por condición ===
Cond_A    : 451.51 ms
Cond_B    : 460.24 ms
Cond_C    : 440.86 ms

=== Conteo de 'Mejor_condición' ===
Cond_A    : 9 sujetos
Cond_B    : 9 sujetos
Cond_C    : 12 sujetos

=== Porcentaje de sujetos con mejor respuesta ===
Cond_A    : 30.0%
Cond_B    : 30.0%
Cond_C    : 40.0%
