In [2]:
import matplotlib.pyplot as plt
import scipy.io
import seaborn as sns
import numpy as np
import pandas as pd
import networkx as nx

In [23]:
##EJERCICIO 1
data1 = {'Zigno Zodiacal': ['Sagitario', 'Leo', 'Tauro'],'Edad': [25, 30, 22]}
df = pd.DataFrame(data1)

data2 = {'Zigno Zodiacal': ['Capricornio', 'Géminis', 'Aries'],'Edad': [45, 19, 33]}
df2 = pd.DataFrame(data2)
df_concatenado = pd.concat([df, df2], axis=0)
df_concatenado

Zigno Zodiacal  Edad
0      Sagitario    25
1            Leo    30
2          Tauro    22
0    Capricornio    45
1        Géminis    19
2          Aries    33

In [34]:
##EJERCICIO 2
mu, sigma= 0, 1000
data= np.random.uniform(mu, sigma, size=[30, 1])
df_Enero =pd.DataFrame(data, columns=['Ventas'])
df_Enero['Mes'] = 'Enero'
df_Enero
df_Febrero=pd.DataFrame(data, columns=['Ventas'])
df_Febrero['Mes'] = 'Febrero'
df_Febrero

df_ventas = pd.concat([df_Enero, df_Febrero], axis=0)
df_ventas


Ventas      Mes
0   851.413167    Enero
1   890.504362    Enero
2   924.231061    Enero
3   545.980268    Enero
4   197.360220    Enero
5   489.494479    Enero
6   537.481610    Enero
7   106.022413    Enero
8   748.607384    Enero
9   953.767183    Enero
10  855.599760    Enero
11  635.268694    Enero
12   29.576543    Enero
13  920.510534    Enero
14  175.962183    Enero
15  447.883515    Enero
16  944.370521    Enero
17  180.369606    Enero
18  514.369735    Enero
19  936.392588    Enero
20  378.016016    Enero
21  795.045218    Enero
22  664.908256    Enero
23  282.789822    Enero
24  359.929930    Enero
25   68.915070    Enero
26  885.595219    Enero
27  650.964086    Enero
28  473.105286    Enero
29  678.086873    Enero
0   851.413167  Febrero
1   890.504362  Febrero
2   924.231061  Febrero
3   545.980268  Febrero
4   197.360220  Febrero
5   489.494479  Febrero
6   537.481610  Febrero
7   106.022413  Febrero
8   748.607384  Febrero
9   953.767183  Febrero
10  855.599760  Febrero
11  635.268694  Febrero
12   29.576543  Febrero
13  920.510534  Febrero
14  175.962183  Febrero
15  447.883515  Febrero
16  944.370521  Febrero
17  180.369606  Febrero
18  514.369735  Febrero
19  936.392588  Febrero
20  378.016016  Febrero
21  795.045218  Febrero
22  664.908256  Febrero
23  282.789822  Febrero
24  359.929930  Febrero
25   68.915070  Febrero
26  885.595219  Febrero
27  650.964086  Febrero
28  473.105286  Febrero
29  678.086873  Febrero

In [45]:
#EJERCICIO 3
mu, sigma= 0, 100
data1= np.random.uniform(mu, sigma, size=[10, 2])
df1 =pd.DataFrame(data1, columns=['Producto', 'Ventas'])
data2= np.random.uniform(25, 50, size=[10, 2])
df2 =pd.DataFrame(data2, columns=['Descuentos', 'Producto'])

df1y2 = pd.concat([df1, df2], axis=0)
df_chido= df1y2.fillna(value=0)
df_chido

Producto     Ventas  Descuentos
0  45.722737  38.417285    0.000000
1  27.875614  47.073219    0.000000
2  15.885096  88.664588    0.000000
3  34.567814  45.435246    0.000000
4   5.945843  39.454203    0.000000
5  75.416877  39.805627    0.000000
6  22.171440  99.861336    0.000000
7   4.428590  80.712879    0.000000
8  70.538360  70.159771    0.000000
9  58.690400  70.199662    0.000000
0  33.949594   0.000000   26.524697
1  25.651815   0.000000   38.275028
2  42.957908   0.000000   33.867404
3  30.570816   0.000000   37.974522
4  27.352582   0.000000   47.483839
5  35.399637   0.000000   44.424782
6  38.872390   0.000000   36.986543
7  28.723823   0.000000   36.370228
8  39.427051   0.000000   44.403003
9  25.415888   0.000000   38.414651

In [59]:
#EJERCICIO 4
data1 = {'Alumno': ['Roy', 'Roy', 'Roy',],'Nota': [8, 9, 10]}
df1 = pd.DataFrame(data1)
data2= {'Alumno': ['Rodrigo', 'Rodrigo', 'Rodrigo'],'Nota': [10, 9, 8]}
df2 = pd.DataFrame(data2)
data3 = {'Alumno': ['Javi', 'Javi', 'Javi'],'Nota': [10, 8, 9]}
df3 = pd.DataFrame(data3)

df_notas = pd.concat([df1, df2, df3], axis=0, ignore_index=True)
df_notas

Alumno  Nota
0      Roy     8
1      Roy     9
2      Roy    10
3  Rodrigo    10
4  Rodrigo     9
5  Rodrigo     8
6     Javi    10
7     Javi     8
8     Javi     9

In [67]:
# EJERCICIO 5
lista= ['1','2','3','4','5','6','6','4','3','2','1','2','5','5','6','7','7','7','7','7','9','0','0','0','8']
lista_sin=[]
for elemento in lista:
    if elemento not in lista_sin:
        lista_sin.append(elemento)

print(lista_sin)


['1', '2', '3', '4', '5', '6', '7', '9', '0', '8']


In [71]:
# EJERCICIO 6
tupla= [("a", 3), ("b", 1), ("c", 2)]
tupla_ordenada= sorted(tupla, key=lambda elemento: elemento[1])
tupla_ordenada

[('b', 1), ('c', 2), ('a', 3)]

In [95]:
# EJERCICIO 7
n=15
lista = []
for i in range(1, n + 1):
    Multiplo= 7 * i
    lista.append(Multiplo)

lista

[7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98, 105]

In [103]:
# EJERCICIO 8
lista = [ "reconocer", "python", "kayak", "ejercicio", "sometemos", "programar"]
listaPal=[]

palindromo = lambda palabra: palabra.lower() == palabra.lower()[::-1]

for palabra in lista:
    if palindromo(palabra):
        listaPal.append(palabra)

listaPal

['reconocer', 'kayak', 'sometemos']

In [112]:
# EJERCICIO 9
LA= [1,2,3,4,5,6,7,8,9,]
LB= [1,3,5,7,9,]

A= set(LA)
B= set(LB)
Inters_AB= A.intersection(B)

DiferenciaA= A.difference(B)

I_D= (Inters_AB, DiferenciaA)
I_D

({1, 3, 5, 7, 9}, {2, 4, 6, 8})

In [130]:
# EJERCICIO 10
LA= [1,2,3,4,5,6,7,8,9,]
LB= [1,3,5,7,9,]

A= set(LA)
B= set(LB)

def subconjunto(A,B):
    if A.issubset(B):
        return True
    else:
        return False

subconjunto(A, B)
subconjunto(B, A)

True

In [136]:
#EJERCICIO 11
lista= ['1','2','3','4','5','6','6','4','3','2','1','2','5','5','6','7','7','7','7','7','9','0','0','0','8']
lista_unicos= set(lista)
len(lista_unicos)


10

In [149]:
#EJERCICIO 12
import re
lista_de_frases = [
    "El perro corre y el perro salta en el jardín.",
    "La casa es grande, la casa es hermosa y la casa tiene un árbol.",
    "Hoy es un buen día, un día para aprender Python.",
    "El río fluye, fluye, y se lleva las hojas viejas.",
    "Tengo un gato, un perro, y un loro; el gato duerme."
] #Esto fue de chat

palabras_totales = []

for frase in lista_de_frases:
    frase_limpia = frase.lower()
    palabras = re.findall(r'\b\w+\b', frase_limpia)
    palabras_totales.extend(palabras)
palabras_unicas = list(set(palabras_totales))

print(palabras_unicas)

Lista de palabras únicas:
['es', 'hojas', 'para', 'gato', 'grande', 'lleva', 'en', 'hermosa', 'buen', 'río', 'jardín', 'el', 'la', 'las', 'se', 'hoy', 'fluye', 'aprender', 'python', 'duerme', 'tiene', 'árbol', 'loro', 'salta', 'casa', 'tengo', 'corre', 'día', 'perro', 'un', 'viejas', 'y']


In [170]:
# EJERCICIO 13
def obtener_persona_mayor(lista_tuplas):
    if not lista_tuplas:
        return None
    tupla_mayor = max(lista_tuplas, key=lambda persona: persona[1])

    return tupla_mayor

lista_personas = [("Sofía", 30), ("Andrés", 24), ("Valentina", 45), ("Ricardo", 89), ("Mariana", 37), ("Jorge", 52)]

resultado = obtener_persona_mayor(lista_personas)
print(resultado)

('Ricardo', 89)


In [172]:
#EJERCICIO 14
def convertir_listas_a_tuplas(lista_de_listas):
    nueva_lista_de_tuplas = [tuple(sublista) for sublista in lista_de_listas]
    return nueva_lista_de_tuplas

Lista = [[1, 7, 8,], ["Monse", "Billar", "Peda"]]
convertir_listas_a_tuplas(Lista)

[(1, 7, 8), ('Monse', 'Billar', 'Peda')]

In [174]:
# EJERCICIO 15
def sumar_tupla_desempaquetada(tupla_numeros):
    a, b, c = tupla_numeros
    return a + b + c

tupla_1 = (10, 20, 30)
resultado1 = sumar_tupla_desempaquetada(tupla_1)
print(f"La suma de {tupla_1} es: {resultado1}")

tupla_2 = (5.5, 1.2, 3.3)
resultado2 = sumar_tupla_desempaquetada(tupla_2)
print(f"La suma de {tupla_2} es: {resultado2}")

La suma de (10, 20, 30) es: 60
La suma de (5.5, 1.2, 3.3) es: 10.0


In [179]:
#EJERCICIO 16
def ex16_sort_product_price(prod_price_list):
    lista_ordenada = sorted(prod_price_list, key=lambda item: item[1])
    return lista_ordenada

productos = [
    ("Laptop", 1200),
    ("Switch", 50),
    ("Xbox", 300),
    ("Calzones", 25)
]

ex16_sort_product_price(productos)

[('Calzones', 25), ('Switch', 50), ('Xbox', 300), ('Laptop', 1200)]

In [185]:
#EJERCICIO 17
from collections import Counter
def ex17_char_frequency(s):
    return Counter(s)

ex17_char_frequency('Banana')

Counter({'a': 3, 'n': 2, 'B': 1})

In [189]:
# EJERCICIO 18
def ex19_invert_dictionary(d):
    return {v: k for k, v in d.items()}

Dic = {"a": 1, "b": 2}

ex19_invert_dictionary(Dic)

{1: 'a', 2: 'b'}

In [193]:
#EJERCICIO 19
def ex20_merge_dicts_sum_values(a,b):
    merged = d1.copy()
    for k, v in d2.items():
        merged[k] = merged.get(k, 0) + v
    return merged
    d1={"a": 10, "b": 20}
    d2={"b": 5, "c": 30}
    ex20_merge_dicts_sum_values(d1,d2)

In [203]:
#EJERCICIO 20
def ex20_merge_dicts_sum_values(d1,d2):
    merged = d1.copy()
    for k, v in d2.items():
        merged[k] = merged.get(k, 0) + v
    return merged
d1={"a": 10, "b": 20}
d2={"b": 5, "c": 30}

ex20_merge_dicts_sum_values(d1,d2)

{'a': 10, 'b': 25, 'c': 30}

In [200]:
#EJERCICIO 21
def ex21_numpy_array_set_fifth():
    arr = np.zeros(10)
    arr[4] = 1
    return arr

ex21_numpy_array_set_fifth()

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [212]:
#EJERCICIO 22
def ex22_numpy_matrix_3x3():
    return np.arange(9).reshape(3, 3)

ex22_numpy_matrix_3x3()

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [225]:
#EJERCICIO 23
def ex23_numpy_statistics():
    np.random.seed(0)
    arr = np.random.randint(0, 10, 5)
    media = np.mean(arr)
    mediana = np.median(arr)
    desv_std = np.std(arr)
    return (media, mediana, desv_std)

ex23_numpy_statistics()

(np.float64(3.6), np.float64(3.0), np.float64(2.33238075793812))

In [226]:
#EJERCICIO 24
def ex24_numpy_clip_values(arr):
    return np.clip(arr, a_min=None, a_max=10)

arr = [5, 12, 8, 15, 9]
ex24_numpy_clip_values(arr)

array([ 5, 10,  8, 10,  9])

In [228]:
#EJERCICIO 25
def ex25_filter_rows_age_over_30():
    data = {'Nombre': ['Roy', 'Javi', 'Rodrigo'], 'Edad': [25, 45, 31]}
    df = pd.DataFrame(data)
    return df[df['Edad'] > 30]

ex25_filter_rows_age_over_30()

Nombre  Edad
1     Javi    45
2  Rodrigo    31

In [229]:
#EJERCICIO 26
def ex26_load_dict_into_dataframe_and_sort():
    data = {'Nombre': ['X', 'Y', 'Z'], 'Puntaje': [85, 92, 78]}
    df = pd.DataFrame(data)
    return df.sort_values(by='Puntaje', ascending=False)

ex26_load_dict_into_dataframe_and_sort()

Nombre  Puntaje
1      Y       92
0      X       85
2      Z       78

In [230]:
#EJERCICIO 27
def ex27_groupby_mean_value():
    data = {'Grupo': ['A', 'B', 'A'], 'Valor': [10, 20, 14]}
    df = pd.DataFrame(data)
    return df.groupby('Grupo')['Valor'].mean().reset_index()

ex27_groupby_mean_value()

Grupo  Valor
0     A   12.0
1     B   20.0

In [231]:
#EJERCICIO 28
def ex28_most_sold_product_from_sales_df():
    data = {'Producto': ['A', 'B', 'A'], 'Cantidad': [10, 5, 15]}
    df = pd.DataFrame(data) # A=25, B=5
    ventas_totales = df.groupby('Producto')['Cantidad'].sum()
    producto_mas_vendido = ventas_totales.idxmax()
    ventas_max = ventas_totales.max()
    return (producto_mas_vendido, ventas_max)

ex28_most_sold_product_from_sales_df()

('A', np.int64(25))

In [233]:
#EJERCICIO 29
def ex29_map_lambda_cube(lst):
    # Ejemplo: lst = [1, 2, 3]
    return list(map(lambda x: x**3, lst))
lst=[1, 2, 3, 4, 5, 6, 7, 7, 7, 7]

ex29_map_lambda_cube(lst)


[1, 8, 27, 64, 125, 216, 343, 343, 343, 343]

In [234]:
#EJERCICIO 30
def ex30_filter_lambda_even(lst):
    return list(filter(lambda x: x % 2 == 0, lst))

lst=[1, 2, 3, 4, 5]
ex30_filter_lambda_even(lst)

[2, 4]

In [244]:
#EJERCICIO 31
def ex31_sort_list_of_dicts_by_key(lst, keyname):
    return sorted(lst, key=lambda d: d[keyname])

lst = [{'k': 2}, {'k': 1}, {'k': 5}, {'k': 3}]
keyname = 'k'
ex31_sort_list_of_dicts_by_key(lst, 'k')

[{'k': 1}, {'k': 2}, {'k': 3}, {'k': 5}]

In [241]:
#EJERCICIO 32
def ex32_pandas_apply_lambda_uppercase(names_list):
    df = pd.DataFrame({'Nombre': names_list})
    df['Nombre_MAYUS'] = df['Nombre'].apply(lambda x: x.upper())
    return df

names_list=['Javi', 'Naomi', 'Monse', 'Rodrigo']

ex32_pandas_apply_lambda_uppercase(names_list)


Nombre Nombre_MAYUS
0     Javi         JAVI
1    Naomi        NAOMI
2    Monse        MONSE
3  Rodrigo      RODRIGO