In [1]:
from modulo import saludo

In [3]:
saludo()

Saludo


# Paquete numpy

Es un paquete enfocado en manipular información en estructuras conocidas como vectores, arreglo y matrices

La contribución más significativa del paquete numpy es la introducción de un tipo de dato llamado array

In [13]:
import numpy

In [15]:
import numpy as np

In [16]:
lista = [3, 4, 5]

variable = np.array(lista)
type(variable)

numpy.ndarray

In [18]:
variable.ndim

1

In [22]:
#Matriz (son arreglos) - tipo de dato adentro de un py

variable2d = np.array([
    [4, 5 , 6],  #primera dimension
    [7, 8 ,9]    #segunda dimensión [listas de listas]
])
type(variable2d), variable2d.ndim, variable.shape  #Dimension numerica

(numpy.ndarray, 2, (3,))

In [21]:
variable.ndim, variable.shape

(1, (3,))

### Funciones numpy


In [26]:
np.zeros(6), np.zeros((3,4))

(array([0., 0., 0., 0., 0., 0.]),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]))

In [27]:
np.ones(4)

array([1., 1., 1., 1.])

In [29]:
2* np.ones(9)

array([2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [30]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
5* np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [32]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [49]:
# Ejercicio: Crear un arreglo de 4x4 cuyos elementos en la diagonal sea igual a 8, pero fuera de la diagonal sea igual a -10

valor = -10*np.ones([4,4]) + 18*np.eye(4)
valor


array([[  8., -10., -10., -10.],
       [-10.,   8., -10., -10.],
       [-10., -10.,   8., -10.],
       [-10., -10., -10.,   8.]])

In [50]:
valor/2

array([[ 4., -5., -5., -5.],
       [-5.,  4., -5., -5.],
       [-5., -5.,  4., -5.],
       [-5., -5., -5.,  4.]])

In [51]:
valor**2

array([[ 64., 100., 100., 100.],
       [100.,  64., 100., 100.],
       [100., 100.,  64., 100.],
       [100., 100., 100.,  64.]])

In [56]:
1/valor

array([[ 0.125, -0.1  , -0.1  , -0.1  ],
       [-0.1  ,  0.125, -0.1  , -0.1  ],
       [-0.1  , -0.1  ,  0.125, -0.1  ],
       [-0.1  , -0.1  , -0.1  ,  0.125]])

In [57]:
valor**0.5

C:\Users\V304_29\AppData\Local\Temp\ipykernel_6716\1006119973.py:1: RuntimeWarning: invalid value encountered in sqrt
  valor**0.5


array([[2.82842712,        nan,        nan,        nan],
       [       nan, 2.82842712,        nan,        nan],
       [       nan,        nan, 2.82842712,        nan],
       [       nan,        nan,        nan, 2.82842712]])