# 

In [3]:
import numpy as np

In [6]:
# convertir datos a arreglos
value=np.array(5) #si fuese lista seria []
print (f"value= {value}, data type = {type(value)}")

value= 5, data type = <class 'numpy.ndarray'>


In [11]:
np.array(range(-7,6))[2:6] 

array([-5, -4, -3, -2])

In [14]:
a,b = np.arange(5), np.arange (-10,-5)
a,b

(array([0, 1, 2, 3, 4]), array([-10,  -9,  -8,  -7,  -6]))

In [16]:
# ejemplos de suma, resta, multiplicacion, division y modulo de los arrays
b-a
b/3
a + 18

array([18, 19, 20, 21, 22])

In [19]:
1/a

C:\Users\Admin\AppData\Local\Temp\ipykernel_7196\261954055.py:1: RuntimeWarning: divide by zero encountered in divide
  1/a


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ])

In [18]:
b ** (1/a) # nan:non a number. 

C:\Users\Admin\AppData\Local\Temp\ipykernel_7196\1878905493.py:1: RuntimeWarning: divide by zero encountered in divide
  b ** (1/a)
C:\Users\Admin\AppData\Local\Temp\ipykernel_7196\1878905493.py:1: RuntimeWarning: invalid value encountered in power
  b ** (1/a)


array([inf, -9., nan, nan, nan])

In [23]:
-8**(1/2)

-2.8284271247461903

In [25]:
vec=np.array([5, 10 ])
vec

array([ 5, 10])

In [30]:
vec.transpose()

array([[ 4, -7],
       [ 1,  2]])

In [32]:
vec2D= np.array([[4,1],[-7,2]])
vec2D,vec2D.transpose(), vec2D.T

(array([[ 4,  1],
        [-7,  2]]),
 array([[ 4, -7],
        [ 1,  2]]),
 array([[ 4, -7],
        [ 1,  2]]))

In [33]:
vec1 =np.array([[1,2],[3,4]])
vec1,vec2D

(array([[1, 2],
        [3, 4]]),
 array([[ 4,  1],
        [-7,  2]]))

In [35]:
resultado= vec1 @ vec2D # multiplicacion matricial como matematicamente es enseñada

In [39]:
resultado[1][0] #slicing

np.int64(-16)

In [40]:
matriz= np.array ([[0,5,10],[15,20,25],[99,35,40]])
matriz

array([[ 0,  5, 10],
       [15, 20, 25],
       [99, 35, 40]])

In [49]:
matriz[1:]

array([[15, 20, 25],
       [99, 35, 40]])

In [50]:
# tarea:  sacar 2da columna 

In [51]:
matriz[1][0]=-20

In [53]:
np.random.rand(5,3)

array([[0.07785677, 0.66355978, 0.78497776],
       [0.41007985, 0.05938325, 0.47977561],
       [0.34631494, 0.69337198, 0.72139251],
       [0.65177619, 0.51803688, 0.75807141],
       [0.7408112 , 0.25209722, 0.55973923]])