## Bibliotecas, paquetes,modulos

In [1]:
from cosas import * ##mando llamar a mi modulo "cosas", no olvidar actualizar con kernell

In [3]:
funcion()

hola mundo


In [4]:
saludo() 

hola desde el paquete


In [ ]:
## ¡qué es un modulo? es script que contiene variables, funciones y clases 

In [2]:
suma(1,2)

3

# Paquete numpy
Es un paquete enfocado en manipular arreglos de n dimensiones, es decir un arreglo. Un arreglo es una lista númerico con una sola dimension
Numpy no hace matématicos



In [8]:
import numpy as np


In [9]:
lista = [3,4,5]

variable = np.array(lista) ## a esta varible hazmela un arreglo
type (variable)

numpy.ndarray

In [25]:
variable.ndim

1

In [28]:
var2= np.array([
     [4,5,6],
     [7,8,9]
])
type(var2), var2.ndim ## cuantas dimensiones tiene mi variable

(numpy.ndarray, 2)

In [29]:
var2

array([[4, 5, 6],
       [7, 8, 9]])

In [30]:
var2.shape ##los arreglos tmb tienen forma, dos filas 3 columnas

(2, 3)

## funciones de numpy

In [31]:
np.zeros(20), np.zeros([3,4]) ##arreglo de puros ceros, tú argumento son el número de ceros

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.]),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]))

In [35]:
np.ones([4,3,3, 3, 3]) ##arreglos de puros unos

array([[[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]],



       [[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
    

In [38]:
np.eye(3) ##función para crear una matriz de identidad, recordar q las matricez de identidad tienen q ser cuadradois

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np.eye(5) ## crea una matriz de 5*5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
## crar un arreglo de 4x4 cuyos elementos en la diagonal sean=8 y los de afuera=-10

In [62]:
valor= -10*np.ones([4,4])+ 18*np.eye(4) ##puedes sumar arregles, -10+18= 8
print(valor)

[[  8. -10. -10. -10.]
 [-10.   8. -10. -10.]
 [-10. -10.   8. -10.]
 [-10. -10. -10.   8.]]


In [55]:
np.eye(4)*8## puedes multiplicar los argumentos de los arreglos

array([[8., 0., 0., 0.],
       [0., 8., 0., 0.],
       [0., 0., 8., 0.],
       [0., 0., 0., 8.]])

In [59]:
valor/2 ### los arreglos se pueden dividir

array([[ 4., -5., -5., -5.],
       [-5.,  4., -5., -5.],
       [-5., -5.,  4., -5.],
       [-5., -5., -5.,  4.]])

In [60]:
valor**2

array([[ 64., 100., 100., 100.],
       [100.,  64., 100., 100.],
       [100., 100.,  64., 100.],
       [100., 100., 100.,  64.]])

In [63]:
1/valor

array([[ 0.125, -0.1  , -0.1  , -0.1  ],
       [-0.1  ,  0.125, -0.1  , -0.1  ],
       [-0.1  , -0.1  ,  0.125, -0.1  ],
       [-0.1  , -0.1  , -0.1  ,  0.125]])