In [2]:
# 1. Visualizar .mat en Pyhton

# Requiere: scipy
from scipy.io import loadmat

# Cargar archivo .mat
mat_data = loadmat('Coactivation_matrix.mat')

# Mostrar todas las variables y su contenido
for key, value in mat_data.items():
    if not key.startswith('__'):  # omite metadatos internos
        print(f"\n🔹 Variable: {key}")
        print(f"Tipo: {type(value)}")
        print(f"Forma: {getattr(value, 'shape', 'N/A')}")
        print("Contenido:")
        print(value)


🔹 Variable: Coactivation_matrix
Tipo: <class 'numpy.ndarray'>
Forma: (638, 638)
Contenido:
[[0.         0.16071429 0.11148649 ... 0.         0.05045872 0.1011236 ]
 [0.16071429 0.         0.06825939 ... 0.         0.         0.06923077]
 [0.11148649 0.06825939 0.         ... 0.03412969 0.         0.        ]
 ...
 [0.         0.         0.03412969 ... 0.         0.         0.        ]
 [0.05045872 0.         0.         ... 0.         0.         0.09777778]
 [0.1011236  0.06923077 0.         ... 0.         0.09777778 0.        ]]

🔹 Variable: Coord
Tipo: <class 'numpy.ndarray'>
Forma: (638, 3)
Contenido:
[[ 7.24363636 37.01090909  9.42545455]
 [ 7.98653199 46.22222222 15.60942761]
 [ 7.55725191 33.83206107 23.51145038]
 ...
 [-4.92385787 15.31979695 27.73604061]
 [-6.27312775 34.70484581 -5.09251101]
 [-4.53874539 46.53874539  3.06273063]]


In [ ]:
# 2. Convertir .mat a .xlsx

# Requiere: scipy (ya usado arriba) y pandas
import pandas as pd

mat_data = loadmat('Coactivation_matrix.mat')

# Exportar cada variable a una hoja de Excel
with pd.ExcelWriter('Coactivation_matrix.xlsx') as writer:
    for key, value in mat_data.items():
        if not key.startswith('__'):
            try:
                df = pd.DataFrame(value)
                df.to_excel(writer, sheet_name=key, index=False)
            except Exception as e:
                print(f"No se pudo exportar '{key}': {e}")

In [7]:
# 3. VIsualizar .edf en Python

# Requiere: mne
import mne

# Cargar archivo EDF
raw = mne.io.read_raw_edf('chb01_01.edf', preload=True)

# Mostrar información general
print(raw.info)
print("Canales:", raw.ch_names)
print(f"Duración: {raw.times[-1]:.2f} segundos")
print(f"Frecuencia de muestreo: {raw.info['sfreq']} Hz")

Extracting EDF parameters from C:\Users\apgso\OneDrive\Documentos\modelos-2026-1\Neurociencias-2026-1\S04_parciales\parcial-2\chb01_01.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 921599  =      0.000 ...  3599.996 secs...


C:\Users\apgso\AppData\Local\Temp\ipykernel_8628\3980214832.py:7: RuntimeWarning: Channel names are not unique, found duplicates for: {'T8-P8'}. Applying running numbers for duplicates.
  raw = mne.io.read_raw_edf('chb01_01.edf', preload=True)


<Info | 8 non-empty values
 bads: []
 ch_names: FP1-F7, F7-T7, T7-P7, P7-O1, FP1-F3, F3-C3, C3-P3, P3-O1, ...
 chs: 23 EEG
 custom_ref_applied: False
 highpass: 0.0 Hz
 lowpass: 128.0 Hz
 meas_date: 2076-11-06 11:42:54 UTC
 nchan: 23
 projs: []
 sfreq: 256.0 Hz
 subject_info: <subject_info | his_id: Surrogate>
>
Canales: ['FP1-F7', 'F7-T7', 'T7-P7', 'P7-O1', 'FP1-F3', 'F3-C3', 'C3-P3', 'P3-O1', 'FP2-F4', 'F4-C4', 'C4-P4', 'P4-O2', 'FP2-F8', 'F8-T8', 'T8-P8-0', 'P8-O2', 'FZ-CZ', 'CZ-PZ', 'P7-T7', 'T7-FT9', 'FT9-FT10', 'FT10-T8', 'T8-P8-1']
Duración: 3600.00 segundos
Frecuencia de muestreo: 256.0 Hz


In [ ]:
# 4. Convertir .edf a .xlsx

# Requiere: pandas y mne (ya usados arriba)

# Extraer datos y tiempos
data, times = raw.get_data(return_times=True)

# Crear DataFrame sin modificar datos
df = pd.DataFrame(data.T, columns=raw.ch_names)
df.insert(0, 'Time (s)', times)

# Exportar a Excel
df.to_excel('chb01_01.xlsx', index=False)