In [3]:
!pip install numpy

zsh:1: command not found: pip


In [4]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [9]:
# Convertir de datos a arreglos

value = np.array(5.)
print(f"value = {value}, data type = {type(value)}")

value = 5.0, data type = <class 'numpy.ndarray'>


In [10]:
np.array(5)

array(5)

In [11]:
np.array(range(-7,6))[2:6]

array([-5, -4, -3, -2])

In [13]:
a, b = np.arange(5), np.arange(-10, -5)
a , b

(array([0, 1, 2, 3, 4]), array([-10,  -9,  -8,  -7,  -6]))

In [14]:
a + b

array([-10,  -8,  -6,  -4,  -2])

In [15]:
b - a

array([-10, -10, -10, -10, -10])

In [16]:
6*a

array([ 0,  6, 12, 18, 24])

In [17]:
a/3

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333])

In [18]:
a + 18

array([18, 19, 20, 21, 22])

In [19]:
a**3  # potencia

array([ 0,  1,  8, 27, 64])

In [20]:
a * b

array([  0,  -9, -16, -21, -24])

array([ 0, -1, -1, -1, -1])

In [22]:
b / a  #no se puede dividir entre 0

C:\Users\V304-23\AppData\Local\Temp\ipykernel_9984\1491818542.py:1: RuntimeWarning: divide by zero encountered in divide
  b / a


array([       -inf, -9.        , -4.        , -2.33333333, -1.5       ])

In [23]:
a ** b

ValueError: Integers to negative integer powers are not allowed.

In [24]:
a ** (1/3)  #raiz cubica

array([0.        , 1.        , 1.25992105, 1.44224957, 1.58740105])

In [25]:
b ** a

array([   1,   -9,   64, -343, 1296])

In [26]:
b**(1/a)  #El error viene del infinito y de 0

C:\Users\V304-23\AppData\Local\Temp\ipykernel_9984\3261360213.py:1: RuntimeWarning: divide by zero encountered in divide
  b**(1/a)
C:\Users\V304-23\AppData\Local\Temp\ipykernel_9984\3261360213.py:1: RuntimeWarning: invalid value encountered in power
  b**(1/a)


array([inf, -9., nan, nan, nan])

In [27]:
a ** (0.5)  #raiz cuadrada

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [28]:
64 ** (1/4)

2.8284271247461903

In [29]:
27 ** (1/3)

3.0

In [30]:
121**(0.5)

11.0

In [31]:
121**(1/2)

11.0

In [36]:
-8 **(0.5), (-6) ** (1/4)

(-2.8284271247461903, (1.1066819197003217+1.1066819197003217j))

In [34]:
(-8)**(1/2) #Forma un número complejo

(1.7319121124709868e-16+2.8284271247461903j)

In [35]:
(-7) ** (1/3)

(0.9564655913861947+1.656646999972302j)

In [37]:
vec = np.array([5, 10])
vec

array([ 5, 10])

In [38]:
vec.transpose()

array([ 5, 10])

In [40]:
vec2D = np.array([[4, -1], [-7,2]])
vec2D     #MATRIZ

array([[ 4, -1],
       [-7,  2]])

In [41]:
vec2D.transpose(), vec2D.T  #operacion arroba (producto matricial)

(array([[ 4, -7],
        [-1,  2]]),
 array([[ 4, -7],
        [-1,  2]]))

In [42]:
vec1= np.array([[1, 2], [3, 4]])
vec1, vec2D

(array([[1, 2],
        [3, 4]]),
 array([[ 4, -1],
        [-7,  2]]))

In [44]:
resultado = vec1 @ vec2D  #Aquí multiplican filas con columnas
resultado

array([[-10,   3],
       [-16,   5]])

In [49]:
resultado[1] [0]  #Doble slicing

np.int64(-16)

In [46]:
resultado[1]

array([-16,   5])

In [47]:
resultado[0]

array([-10,   3])

In [2]:
matriz = np.array([[0,5,10],
                   [15, 20, 25],
                   [99, 35, 40]])

NameError: name 'np' is not defined

In [51]:
matriz [2][0:-1]

array([99, 35])

In [52]:
matriz [:][:]

array([[ 0,  5, 10],
       [15, 20, 25],
       [99, 35, 40]])

In [64]:
matriz [1:][:] 

array([[15, 20, 25],
       [99, 35, 40]])

In [65]:
matriz [1:]

array([[15, 20, 25],
       [99, 35, 40]])

In [1]:
# Tarea ver el slicing para obtener los datos de la columna de enmedio

matriz [:,1]

NameError: name 'matriz' is not defined

In [66]:
matriz[1][0] = -20
matriz

array([[  0,   5,  10],
       [-20,  20,  25],
       [ 99,  35,  40]])

In [71]:
for _ in range (5):
   print(np.random.rand())   #Números aleatorios entre 0 y 1

0.7442528585517413
0.6841172288859179
0.6732878698518411
0.220551597852236
0.9871316036201888


In [72]:
np.random.rand(5,3)  #Genera una matriz

array([[0.50530137, 0.4806198 , 0.63053671],
       [0.22832816, 0.21607094, 0.1521362 ],
       [0.16503958, 0.75099994, 0.22580131],
       [0.33918528, 0.11831692, 0.07822309],
       [0.59332409, 0.02695806, 0.46024055]])