In [7]:
import pandas as pd
import numpy as np    

# CONCATENAR

In [25]:
##Ejercicio 1
def ex1_concat_same_structure(data1, data2):
    d1=pd.DataFrame( data1)
    d2=pd.DataFrame( data2)
    return(pd.concat([d1, d2], ignore_index=True))
ex1_concat_same_structure(data1=({"Nombre":["Martin","James","Keonho"], "Edad":["17","20","16"]}),
                          data2=({"Nombre":["RM","JK","Hobi"], "Edad":["30","27","28"]}))

Nombre Edad
0  Martin   17
1   James   20
2  Keonho   16
3      RM   30
4      JK   27
5    Hobi   28

In [38]:
#Ejercicio 2
def ex2_concat_with_month_column(mes):
    ventas=pd.DataFrame({"ventas":["20","30","25","40","35"]})
    mes=pd.DataFrame(mes)
    return(ventas.join(mes))
ex2_concat_with_month_column({"meses":["Enero","Febrero","Marzo","Abril","Mayo"]})


ventas    meses
0     20    Enero
1     30  Febrero
2     25    Marzo
3     40    Abril
4     35     Mayo

In [28]:
#Ejercicio3
def ex3_concat_diff_columns_fillna():
    ventas=pd.DataFrame({"Productos":["1","2","3","4","5"], "Ventas":["50","40", "35", "20","25" ]})
    productos= pd.DataFrame({"Productos":["1","2","4"], "Descuento":["15%","15%","10%"]})
    m=pd.merge(ventas,productos, on=["Productos"], how="outer")
    print(m.fillna(0))
ex3_concat_diff_columns_fillna()

  Productos Ventas Descuento
0         1     50       15%
1         2     40       15%
2         3     35         0
3         4     20       10%
4         5     25         0


In [46]:
#Eejercicio 4
def ex4_concat_three_groups():
    g_1 = pd.DataFrame({"Alumno": ["A1","A2","A3"], "Nota": [9, 9, 8] })
    g_2 = pd.DataFrame({"Alumno": ["B1","B2","B3"], "Nota": [9, 8, 10] })
    g_3 = pd.DataFrame({ "Alumno": ["C1","C2","C3"], "Nota": [10, 9, 9]})
  
    pint(pd.concat([g_1,g_2,g_3], ignore_index=True) )
ex4_concat_three_groups()

  Alumno  Nota
0     A1     9
1     A2     9
2     A3     8
3     B1     9
4     B2     8
5     B3    10
6     C1    10
7     C2     9
8     C3     9


# LISTAS

In [ ]:
#Ejercicio 5
def ex5_remove_duplicates_preserve_order(lista):
    lista_nueva=[]
    for  caracter in lista:
       if caracter not in lista_nueva:
           lista_nueva.append(caracter)   
    return lista_nueva
ex5_remove_duplicates_preserve_order(list("parangaricutirimicuaro"))  

In [ ]:
#Ejercicio 6
def ex6_sort_tuples_by_second_element(tuplas):
    lista_ordenada = sorted(tuplas, key=lambda x:x[1])
    return lista_ordenada
ex6_sort_tuples_by_second_element([("a", 3), ("b", 1), ("c", 2)])

In [81]:
#Ejercicio 7
def ex7_first_n_multiples_of_7(n):
    múltiplos = [7**x for x in range(n)]
    return múltiplos
ex7_first_n_multiples_of_7(5)  


[1, 7, 49, 343, 2401]

In [113]:
#Ejercicio 8
def ex8_filter_palindromes(cadenas):
    palíndromos=[]
    for elemento in cadenas:
         if elemento==elemento[::-1]:
             palíndromos.append(elemento)
    return palíndromos
ex8_filter_palindromes(["Hola","babosos","mi", "ava", "reconocer","azul","ilili"])
 


['ava', 'reconocer', 'ilili']

# Conjuntos

In [100]:
#Ejercicio 9
def ex9_set_intersection_and_difference(set_a, set_b):
    interseccion=[]
    diferencia=[]
    for elemento in set_a:
       if elemento in set_b:
           interseccion.append(elemento)
       else:
           if elemento not in set_b:
               diferencia.append(elemento)
    return(interseccion,diferencia)
ex9_set_intersection_and_difference({1,2,3},{1,2,4})     


([1, 2], [3])

In [109]:
#Ejercicio 10
def ex10_is_subset(set_a, set_b):
   return set_a.issubset(set_b)
ex10_is_subset({1,2,3},{1,2,3,4,5,6})

True

In [11]:
#Ejericio 11
def ex11_count_unique_elements(lst):
    set_l=set(lst)
    return(len(set_l))
ex11_count_unique_elements(list("parangaricutirimicuaro"))

11

In [78]:
#Ejercicio 12
def ex12_unique_words_from_phrases(phrases):
    b=set()
    for frase in phrases:
        for palabra in  frase.split():
         b.add(palabra)
    return(b)
    
         
ex12_unique_words_from_phrases(["Hola mundo", "Hola a todos", "Hola mundo a todos"])

{'Hola', 'a', 'mundo', 'todos'}

# Tuplas

In [6]:
#Ejercicio 13
def ex13_oldest_person(tuple_list):
    return (max(tuple_list, key=lambda x:x[1]))
ex13_oldest_person([("Mon", 20), ("Bibi", 21), ("Pepe", 16)])

('Bibi', 21)

In [19]:
#Ejercicio 14
def ex14_convert_list_of_lists_to_tuples(list_of_lists):
    return( tuple(tuple(lista) for lista in list_of_lists))
ex14_convert_list_of_lists_to_tuples([[1, 2], [3, 4], [5, 6]])

((1, 2), (3, 4), (5, 6))

In [27]:
#Ejericio 15
def ex15_sum_of_tuple_abc(tupla):
    return ((int(sum (set(tupla)))))
(ex15_sum_of_tuple_abc([1,2,3]))

6

In [40]:
#Ejercicio 16
def ex16_sort_product_price(lista_de_tuplas):
    return(sorted(lista_de_tuplas, key=lambda x:x[1])) #sorted funciona con cualquier iterable
ex16_sort_product_price([["pasta", 24], ["frijol",32], ["lentejas",20]])

[['lentejas', 20], ['pasta', 24], ['frijol', 32]]

# Diccionarios

In [64]:
#Ejericicio 17
def ex17_char_frequency(s):
    diccionario={}
    for caracter in s:
        if caracter in diccionario:
           diccionario[caracter]+=1
        else:
            diccionario[caracter]=1
    return diccionario
ex17_char_frequency("Parangaricutirimicuaro")

{'P': 1,
 'a': 4,
 'r': 4,
 'n': 1,
 'g': 1,
 'i': 4,
 'c': 2,
 'u': 2,
 't': 1,
 'm': 1,
 'o': 1}

In [117]:
#Ejericio 18
def ex18_best_student(grades_dict):
 valor=max(grades_dict.values())
 for k in grades_dict:
    if grades_dict[k]==valor:
        return(k,valor)
    
ex18_best_student({"Pablo": 7, "Alejandro":9, "Roberto":7, "María":10})

('María', 10)

In [128]:
#Ejercicio 19
def ex19_invert_dictionary(d):
    new={}
    for k, v in d.items():
        new[v]=k
    return new
ex19_invert_dictionary({"Pablo": 7, "Alejandro":9, "Roberto":7, "María":10})

{7: 'Roberto', 9: 'Alejandro', 10: 'María'}

In [141]:
#Ejercicio 20
def ex20_merge_dicts_sum_values(d1, d2):
    for key, value in d2.items():
        if key in d1:
            d1[key] += value
        else:
            d1[key] = value
    return d1
ex20_merge_dicts_sum_values({"Pablo": 7, "Alejandro":9, "Roberto":7, "María":10}, {"Pablo": 7, "Isabel":9, "Roberto":7, "Mari":10})

{'Pablo': 14,
 'Alejandro': 9,
 'Roberto': 14,
 'María': 10,
 'Isabel': 9,
 'Mari': 10}

# Numpy

In [142]:
import numpy as np

In [163]:
#Ejercico 21
def ex21_numpy_array_set_fifth():
    b=np.zeros(10)
    b[4]=5
    return b
ex21_numpy_array_set_fifth()

array([0., 0., 0., 0., 5., 0., 0., 0., 0., 0.])

In [166]:
def ex22_numpy_matrix_3x3():
    matriz=np.random.uniform(0,8, size=[3,3])
    return matriz
ex22_numpy_matrix_3x3()

array([[3.80759524, 2.93161202, 5.62811419],
       [7.54751402, 3.13690068, 4.83660772],
       [1.6593343 , 4.25596421, 4.76660737]])

In [164]:
#Ejercicio 22
def ex23_numpy_statistics():
    array= np.array(20)
    """Ejercicio 23:
    Genera un array aleatorio de 20 enteros y calcula la media, mediana y desviación estándar.
    Retorna una tupla (media, mediana, desviación estándar).
    """
    pass

array([[0.47718295, 5.12274454, 2.82530697],
       [7.2858175 , 7.83368745, 0.98186892],
       [0.55652174, 7.55182019, 2.07828097]])

In [167]:
np.array(20)

array(20)