# TAREA

## Tarea el 2do parcial


Cada ejercicio está representado por una función con su docstring que contiene
la instrucción (no incluye soluciones). Implementa las funciones por tu cuenta.

In [1]:
import pandas as pd
import numpy as np

### 1- 4 Pandas (concatenación)

In [83]:
def ex1_concat_same_structure():
    data1 = pd.DataFrame({"Nombre": ["Ana", "Meche", "Paola"], "Edad": [20, 25, 30]})
    data2 = pd.DataFrame({"Nombre": ["Taylor Swift", "Sofía", "Carlos"], "Edad": [22, 28, 35]})
    return pd.concat([data1, data2])


print(ex1_concat_same_structure())

         Nombre  Edad
0           Ana    20
1         Meche    25
2         Paola    30
0  Taylor Swift    22
1         Sofía    28
2        Carlos    35


In [59]:
def ex2_concat_with_month_column():
    enero = pd.DataFrame({"Venta": [100, 200, 150]})
    febrero = pd.DataFrame({"Venta": [120, 180, 170]})
    enero["Mes"] = "Enero"
    febrero["Mes"] = "Febrero"
    df = pd.concat([enero, febrero])
    return df

print(ex2_concat_with_month_column())

   Venta      Mes
0    100    Enero
1    200    Enero
2    150    Enero
0    120  Febrero
1    180  Febrero
2    170  Febrero


In [72]:
def ex3_concat_diff_columns_fillna():
    df1 = pd.DataFrame({"Producto": ["A", "B"], "Ventas": [10, 20]})
    df2 = pd.DataFrame({"Producto": ["C", "D"], "Descuento": [5, 3]})
    return pd.concat([df1, df2]).fillna(0)
    
print(ex3_concat_diff_columns_fillna())

  Producto  Ventas  Descuento
0        A    10.0        0.0
1        B    20.0        0.0
0        C     0.0        5.0
1        D     0.0        3.0


In [30]:
def ex4_concat_three_groups():
    g1 = pd.DataFrame({"Grupo": ["A", "A", "A"], "Nota": [8, 9, 7]})
    g2 = pd.DataFrame({"Grupo": ["B", "B", "B"], "Nota": [6, 7, 8]})
    g3 = pd.DataFrame({"Grupo": ["C", "C", "C"], "Nota": [ 9, 9, 10]})
    df = pd.concat([g1, g2, g3])
    return df

print(ex4_concat_three_groups())

  Grupo  Nota
0     A     8
1     A     9
2     A     7
0     B     6
1     B     7
2     B     8
0     C     9
1     C     9
2     C    10


### 5-8 Listas

In [31]:
def ex5_remove_duplicates_perserve_order(list):
    nueva = []
    for x in list:
        if x not in nueva:
            nueva.append(x)
    return nueva

print(ex5_remove_duplicates_perserve_order([1, 2, 2, 3, 1, 4]))

[1, 2, 3, 4]


In [32]:
def ex6_sort_tuples_by_second_element(tuples_list):
    return sorted(tuples_list, key=lambda x: x[1])

print(ex6_sort_tuples_by_second_element([("a", 3), ("b", 1), ("c", 2)]))

[('b', 1), ('c', 2), ('a', 3)]


In [34]:
def ex7_first_n_multiples_of_7(n):
    return [7 * i for i in range(1,n + 1)]

print(ex7_first_n_multiples_of_7(5))

[7, 14, 21, 28, 35]


In [37]:
def ex8_filter_palindromes(strings):
    return [s for s in strings if s == s[::-1]]

print(ex8_filter_palindromes(["oso", "casa", "ana", "sol"]))

['oso', 'ana']


### 9-12 Conjuntos

In [38]:
def ex9_set_intersection_and_difference(set_a, set_b):
    inter = set_a & set_b
    diff = set_a - set_b
    return inter, diff

print(ex9_set_intersection_and_difference({1, 2, 3}, {2, 3, 4}))

({2, 3}, {1})


In [39]:
def ex10_is_subset(set_a, set_b):
    return set_a.issubset(set_b)

print(ex10_is_subset({1, 2}, {1, 2, 3}))

True


In [40]:
def ex11_count_unique_elements(list):
    return len(set(list))

print(ex11_count_unique_elements([1, 1, 2, 3, 3, 4]))

4


In [42]:
def ex12_unique_words_from_phrases(phrases):
    palabras = set()
    for frase in phrases:
        for p in frase.split():
            palabras.add(p)
    return palabras

print(ex12_unique_words_from_phrases(["hola mundo", "mundo feliz", "hola a todos"]))

{'todos', 'a', 'mundo', 'hola', 'feliz'}


### 13-16: Tuplas

In [44]:
def ex13_oldest_person(tuple_list):
    return max(tuple_list, key= lambda x: x[1])

print(ex13_oldest_person([("Ana", 20), ("Meche", 30), ("Paola", 25)]))

('Meche', 30)


In [86]:
def ex14_convert_list_of_list_to_tuples(list_of_lists):
    return [tuple(x) for x in list_of_lists]

display(ex14_convert_list_of_list_to_tuples([[1, 2], [3, 4], [5, 6]]))

[(1, 2), (3, 4), (5, 6)]

In [46]:
def ex15_sum_of_tuple_abc(t):
    a, b, c = t
    return a + b + c

print(ex15_sum_of_tuple_abc((3, 4, 5)))

12


In [48]:
def ex16_sort_product_price(prod_price_list):
    return sorted(prod_price_list, key=lambda x: x[1])

print(ex16_sort_product_price([("pan", 10), ("leche", 8), ("huevo", 12)]))

[('leche', 8), ('pan', 10), ('huevo', 12)]


### 17-20: Diccionarios

In [49]:
def ex17_char_frequency(s):
    d= {}
    for c in s:
        d[c] = d.get(c, 0) + 1
    return d

print(ex17_char_frequency("banana"))

{'b': 1, 'a': 3, 'n': 2}


In [50]:
def ex18_best_student(grades_dict):
    best = max(grades_dict.items(), key=lambda x: x[1])
    return best

print(ex18_best_student({"Ana": 90, "Meche": 85, "Paola": 95}))

('Paola', 95)


In [61]:
def ex19_invert_dictionary(d):
    return{v: k for k, v in d.items ()}

print(ex19_invert_dictionary({"a": 1, "b": 2, "c": 3}))

{1: 'a', 2: 'b', 3: 'c'}


In [62]:
def ex20_merge_dicts_sum_values(d1, d2):
    resultado = d1.copy()
    for k, v in d2.items():
        resultado[k] = resultado.get(k, 0) + v
    return resultado

print(ex20_merge_dicts_sum_values({"a": 5, "b": 3}, {"a": 2, "c": 4}))

{'a': 7, 'b': 3, 'c': 4}


### 21-24 Numpy

In [65]:
def ex21_numpy_array_set_fifth():
    array = np.zeros(10)
    array[4] = 1
    return array

print(ex21_numpy_array_set_fifth())

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [66]:
def ex22_numpy_matrix_3x3():
    return np.arange(9).reshape(3, 3)

print(ex22_numpy_matrix_3x3())

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [71]:
def ex23_numpy_statistics():
    array = np.random.randint(0, 100, 20)
    media = np.mean(array)
    mediana = np.median(array)
    desviacion = np.std(array)
    return media, mediana, desviacion

print(ex23_numpy_statistics())

(np.float64(56.25), np.float64(53.0), np.float64(29.790728423454166))


In [73]:
def ex24_numpy_clip_values(array):
    array = np.array(array)
    return np.clip(array, None, 10)

print(ex24_numpy_clip_values([3, 7, 12, 15, 8]))

[ 3  7 10 10  8]


### 25-28 Pandas

In [74]:
def ex25_filter_rows_age_over_30():
    df = pd.DataFrame({
        "Nombre": ["Ana", "Meche", "Paola", "Taylor Swift"],
        "Edad": [25, 40, 35, 29],
        "Ciudad": ["CDMX", "GUADALAJARA", "MONTERREY", "PUEBLA"]})
    return df[df["Edad"] > 30]

print(ex25_filter_rows_age_over_30())

  Nombre  Edad       Ciudad
1  Meche    40  GUADALAJARA
2  Paola    35    MONTERREY


In [76]:
def ex26_load_dict_into_dataframe_and_sort():
    data = {"Nombre": ["Ana", "Meche", "Paola"], "Puntaje": [80, 95, 70]}
    df = pd.DataFrame(data)
    return df.sort_values("Puntaje", ascending=False)

print(ex26_load_dict_into_dataframe_and_sort())

  Nombre  Puntaje
1  Meche       95
0    Ana       80
2  Paola       70


In [77]:
def ex27_groupby_mean_value():
    df = pd.DataFrame({
        "Grupo": ["A", "A", "B", "B", "C"],
        "Valor": [10, 20, 30, 40, 50]})
    return df.groupby("Grupo", as_index=False)["Valor"].mean()

print(ex27_groupby_mean_value())

  Grupo  Valor
0     A   15.0
1     B   35.0
2     C   50.0


In [78]:
def ex28_most_sold_product_from_sales_df():
    df = pd.DataFrame({
        "Producto": ["A", "B", "A", "C", "B"],
        "Cantidad": [5, 7, 3, 2, 6]})
    total= df.groupby("Producto")["Cantidad"].sum()
    prod = total.idxmax()
    return prod, total[prod]

print(ex28_most_sold_product_from_sales_df())

('B', np.int64(13))


### 29-32 Lambdas y funciones anónimas

In [81]:
def ex29_map_lambda_cube(lst):
    return list(map(lambda x: x**3, lst))

print(ex29_map_lambda_cube([1, 2, 3, 4]))

[1, 8, 27, 64]


In [82]:
def ex30_filter_lambda_even(lst):
    return list(filter(lambda x: x % 2 == 0, lst))

print(ex30_filter_lambda_even([1, 2, 3, 4, 5, 6]))

[2, 4, 6]


In [84]:
def ex31_sort_list_of_dicts_by_key(lst, keyname):
    return sorted(lst, key=lambda d : d[keyname])

print(ex31_sort_list_of_dicts_by_key([
    {"nombre": "Ana", "edad": 20},
    {"nombre": "Mech", "edad": 30},
    {"nombre": "Paola", "edad": 25}
],"edad"))

[{'nombre': 'Ana', 'edad': 20}, {'nombre': 'Paola', 'edad': 25}, {'nombre': 'Mech', 'edad': 30}]


In [85]:
def ex32_pandas_apply_lambda_uppercase(names_list):
    df = pd.DataFrame({"Nombre": names_list})
    df["Mayusculas"] = df["Nombre"].apply(lambda x : x.upper())
    return df

print(ex32_pandas_apply_lambda_uppercase(["ana", "meche", "paola"]))

  Nombre Mayusculas
0    ana        ANA
1  meche      MECHE
2  paola      PAOLA
