In [3]:
import numpy as np

In [4]:
#convertir datos a arreglos 
value = np.array({5, 'string'})
print(f"value = {value}, data type = {type(value)}")

value = {5, 'string'}, data type = <class 'numpy.ndarray'>


In [7]:
np.array(range(-7, 6)) [2:6]

array([-5, -4, -3, -2])

In [14]:
a, b = np.arange(5), np.arange(-10,-5)
a,b

(array([0, 1, 2, 3, 4]), array([-10,  -9,  -8,  -7,  -6]))

In [15]:
a+b

array([-10,  -8,  -6,  -4,  -2])

In [16]:
b-a

array([-10, -10, -10, -10, -10])

In [17]:
b/3

array([-3.33333333, -3.        , -2.66666667, -2.33333333, -2.        ])

In [18]:
a+18

array([18, 19, 20, 21, 22])

In [19]:
a*b

array([  0,  -9, -16, -21, -24])

In [20]:
b/a

C:\Users\V304-17\AppData\Local\Temp\ipykernel_15204\2243761560.py:1: RuntimeWarning: divide by zero encountered in divide
  b/a


array([       -inf, -9.        , -4.        , -2.33333333, -1.5       ])

In [21]:
a**(1/3)

array([0.        , 1.        , 1.25992105, 1.44224957, 1.58740105])

In [22]:
b**a

array([   1,   -9,   64, -343, 1296])

In [23]:
b**(1/a)

C:\Users\V304-17\AppData\Local\Temp\ipykernel_15204\3261360213.py:1: RuntimeWarning: divide by zero encountered in divide
  b**(1/a)
C:\Users\V304-17\AppData\Local\Temp\ipykernel_15204\3261360213.py:1: RuntimeWarning: invalid value encountered in power
  b**(1/a)


array([inf, -9., nan, nan, nan])

In [24]:
27**(1/3)

3.0

In [25]:
121**(1/2)

11.0

In [26]:
-8**(1/2)

-2.8284271247461903

In [28]:
vec = np.array([5,10])
vec

array([ 5, 10])

In [29]:
vec.transpose()

array([ 5, 10])

In [32]:
vec2D = np.array ([[4,-1],[-7,2]])
vec2D

array([[ 4, -1],
       [-7,  2]])

In [33]:
vec2D.transpose(), vec2D.T #ambas son maneras

(array([[ 4, -7],
        [-1,  2]]),
 array([[ 4, -7],
        [-1,  2]]))

In [34]:
vec1 = np.array([[1,2],[3,4]])
vec1, vec2D

(array([[1, 2],
        [3, 4]]),
 array([[ 4, -1],
        [-7,  2]]))

In [42]:
resultado = vec1 @ vec2D
resultado

array([[-10,   3],
       [-16,   5]])

In [44]:
resultado [1]

array([-16,   5])

In [45]:
matriz = np.array([[0,5,10],
                   [15,20,25],
                   [99,35,40]])

In [46]:
matriz[0][1]

np.int64(5)

In [50]:
matriz[2][0:-1]

array([99, 35])

In [51]:
matriz[:][:]

array([[ 0,  5, 10],
       [15, 20, 25],
       [99, 35, 40]])

In [55]:
matriz[1:]

array([[15, 20, 25],
       [99, 35, 40]])

In [56]:
matriz[1][0]= -20
matriz

array([[  0,   5,  10],
       [-20,  20,  25],
       [ 99,  35,  40]])

In [59]:
for _ in range(5):
    print (np.random.rand()) #genera números aleatorios entre 0 y 1

In [60]:
np.random.rand(5,3)

array([[0.47958926, 0.51446623, 0.17429083],
       [0.94707808, 0.8821562 , 0.41379588],
       [0.51818299, 0.99800609, 0.93935264],
       [0.89113606, 0.78343244, 0.07761836],
       [0.31861439, 0.19674888, 0.6567928 ]])

In [ ]:
#quedarme con la columna de en medio (5,20,35)