In [1]:
import pandas 

In [2]:
import matplotlib

# NUMPY

In [4]:
import numpy as np

In [6]:
# convertir datos a arreglos 
value = np.array ({5, 'string'})
print(f"value = {value}, data type = type{(value)}")

value = {'string', 5}, data type = type{'string', 5}


In [12]:
np.array(range(-7, 6))[2:6]

array([-5, -4, -3, -2])

In [15]:
a, b = np.arange(5), np.arange(-10, -5)
a, b 

(array([0, 1, 2, 3, 4]), array([-10,  -9,  -8,  -7,  -6]))

In [16]:
a + b

array([-10,  -8,  -6,  -4,  -2])

In [17]:
b - a

array([-10, -10, -10, -10, -10])

array([ 0,  6, 12, 18, 24])

In [19]:
b/3

array([-3.33333333, -3.        , -2.66666667, -2.33333333, -2.        ])

In [20]:
a + 18

array([18, 19, 20, 21, 22])

In [21]:
a * b 

array([  0,  -9, -16, -21, -24])

In [23]:
b**a

array([   1,   -9,   64, -343, 1296])

In [24]:
-6**(1/4)

-1.5650845800732873

In [25]:
vec2D = np.array([[4,-1], [-7,2]])
vec2D

array([[ 4, -1],
       [-7,  2]])

In [26]:
vec2D.transpose(),vec2D.T

(array([[ 4, -7],
        [-1,  2]]),
 array([[ 4, -7],
        [-1,  2]]))

In [29]:
vec_2D = np.array ([[1,2],[3,4]])
vec_2D, vec2D

(array([[1, 2],
        [3, 4]]),
 array([[ 4, -1],
        [-7,  2]]))

In [30]:
vec_2D @ vec2D

array([[-10,   3],
       [-16,   5]])

In [31]:
resultado = vec_2D @ vec2D
resultado

array([[-10,   3],
       [-16,   5]])

In [34]:
resultado [1][0]

np.int64(-16)

In [35]:
resultado [1]

array([-16,   5])

In [36]:
matriz = np.array([[0, 5, 10],
                   [15, 20, 25],
                   [99, 35, 40]])

In [37]:
matriz[2][:-1]

array([99, 35])

In [38]:
matriz [:][:]

array([[ 0,  5, 10],
       [15, 20, 25],
       [99, 35, 40]])

In [40]:
matriz [1 :]

array([[15, 20, 25],
       [99, 35, 40]])

In [41]:
# hacer tarea de como nos quedamos con la columna de enmedio (5, 20, 35)

In [42]:
matriz [1][0] = -20
matriz

array([[  0,   5,  10],
       [-20,  20,  25],
       [ 99,  35,  40]])

In [43]:
np.random.rand()

0.5900570189275377

In [44]:
for _ in range(5):
    print (np.random.rand()) # genera nuemeros aleatorios entre 0 y 1

0.3545356642713926
0.5931161129780403
0.3477936532729613
0.9890127037876233
0.5055413622670404


In [45]:
np.random.rand(5)

array([0.56852836, 0.59097124, 0.61908889, 0.60845868, 0.72994306])

In [46]:
np.random.rand(5,3)

array([[0.98632219, 0.61000032, 0.88527424],
       [0.54639015, 0.17679039, 0.98678182],
       [0.97310148, 0.48037263, 0.01007792],
       [0.72625945, 0.15514745, 0.75365319],
       [0.6278919 , 0.7582127 , 0.42876175]])