In [1]:
import numpy as np

In [9]:
# convertir datos a arreglos
value = np.array({5, 'string'})
print(f"value = {value}, data type = {type(value)}")

value = {'string', 5}, data type = <class 'numpy.ndarray'>


In [14]:
np.array(range(-7, 6))[2:6]

array([-5, -4, -3, -2])

In [16]:
a, b = np.arange(5), np.arange(-10, -5)
a, b

(array([0, 1, 2, 3, 4]), array([-10,  -9,  -8,  -7,  -6]))

In [28]:
b**(1/a)

C:\Users\OMEN CI7\AppData\Local\Temp\ipykernel_10724\3261360213.py:1: RuntimeWarning: divide by zero encountered in divide
  b**(1/a)
C:\Users\OMEN CI7\AppData\Local\Temp\ipykernel_10724\3261360213.py:1: RuntimeWarning: invalid value encountered in power
  b**(1/a)


array([inf, -9., nan, nan, nan])

In [31]:
(-8)**0.5, (-6)**(1/4)

((1.7319121124709868e-16+2.8284271247461903j),
 (1.1066819197003217+1.1066819197003217j))

In [32]:
vec = np.array([5, 10])
vec

array([ 5, 10])

In [33]:
vec.transpose()

array([ 5, 10])

In [34]:
vec2D = np.array([[4, -1], [-7, 2]])
vec2D

array([[ 4, -1],
       [-7,  2]])

In [36]:
vec2D.transpose(), vec2D.T

(array([[ 4, -7],
        [-1,  2]]),
 array([[ 4, -7],
        [-1,  2]]))

In [38]:
vec1 = np.array([[1, 2], [3, 4]])
vec1, vec2D

(array([[1, 2],
        [3, 4]]),
 array([[ 4, -1],
        [-7,  2]]))

In [40]:
resultado = vec1 @ vec2D
resultado

array([[-10,   3],
       [-16,   5]])

In [43]:
resultado[1]

array([-16,   5])

In [46]:
matriz = np.array([[0, 5, 10], 
                   [15, 20, 25], 
                   [99, 35, 40]])

In [55]:
matriz[1][0] = -20
matriz

array([[  0,   5,  10],
       [-20,  20,  25],
       [ 99,  35,  40]])

In [59]:
for _ in range(5):
    print(np.random.rand()) # genera números aleatorios entre 0 y 1

0.49170329440724114
0.2578986259706001
0.4022541433042861
0.2938257575267884
0.27201913590045546


In [62]:
np.random.rand(5, 3)

array([[0.25258213, 0.22075809, 0.86468946],
       [0.17269633, 0.45034782, 0.56166916],
       [0.17005711, 0.92343453, 0.24309261],
       [0.32281398, 0.49916833, 0.75110856],
       [0.86634822, 0.46183875, 0.12481121]])