In [7]:
from cosas import saludo

In [11]:
saludo()

hola desde el paquete


In [9]:
from cosas import funcion

In [12]:
funcion()

otra función


In [13]:
### si queremos mandar a llamar a todas las funciones solo ponemos asteristicos
from cosas import *
saludo()

hola desde el paquete


In [8]:
suma(2,3)

5

In [7]:
from cosas import *
funcion2()

otra cosa


## NUMPY
es un paquete enfocado en manipular informacion en estructuras conocidas como vectores, arreglo y matrices
La contribucion mas significativa es la introduccion de un tipo de dato llamado array 

In [5]:
import numpy as np

In [6]:
lista = [3,4,5]

variable = np.array(lista)
type(variable)

numpy.ndarray

In [ ]:
### un arreglo lista numerica con n dimensiones
### una matriz es 

In [16]:
variable.ndim, variable.shape
## ndim dimension numerica, shape dice la forma 

(1, (3,))

In [18]:
variable2d = np.array([
    [4,5,6],
    [7,8,9]
])
type(variable2d), variable2d.ndim, variable2d.shape

### en python todos son arreglos, matrices en matlab
## array es un tipo de dentro de un py??

(numpy.ndarray, 2, (2, 3))

In [15]:
variable2d

array([[4, 5, 6],
       [7, 8, 9]])

### funciones de numpy 

In [19]:
np.zeros(6), np.zeros([3,4])

(array([0., 0., 0., 0., 0., 0.]),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]))

In [20]:
np.ones(4), np.ones([])

(array([1., 1., 1., 1.]), array(1.))

In [21]:
np.ones(4), np.ones([2,3,4])

(array([1., 1., 1., 1.]),
 array([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],
 
        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]))

In [22]:
### matriz identidad??
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.eye(5)
## de 5x5, no puedo hacer una de 2x5 porque siempre son cuadradas 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
## ejer: crear un arreglo de 4x4 cuyos elementos en la diagonal sean igual a 8
# pero fuera de la diagonal sea igual a -10

In [65]:
valor= -10*np.ones([4,4]) + 18*np.eye(4)
valor

array([[  8., -10., -10., -10.],
       [-10.,   8., -10., -10.],
       [-10., -10.,   8., -10.],
       [-10., -10., -10.,   8.]])

In [66]:
valor/2

array([[ 4., -5., -5., -5.],
       [-5.,  4., -5., -5.],
       [-5., -5.,  4., -5.],
       [-5., -5., -5.,  4.]])

In [67]:
valor**2

array([[ 64., 100., 100., 100.],
       [100.,  64., 100., 100.],
       [100., 100.,  64., 100.],
       [100., 100., 100.,  64.]])

In [68]:
valor**0.5

C:\Users\HP\AppData\Local\Temp\ipykernel_38916\1006119973.py:1: RuntimeWarning: invalid value encountered in sqrt
  valor**0.5


array([[2.82842712,        nan,        nan,        nan],
       [       nan, 2.82842712,        nan,        nan],
       [       nan,        nan, 2.82842712,        nan],
       [       nan,        nan,        nan, 2.82842712]])

In [69]:
1/valor
# matematicamente esta operacon no tiene sentido pero en python si 

array([[ 0.125, -0.1  , -0.1  , -0.1  ],
       [-0.1  ,  0.125, -0.1  , -0.1  ],
       [-0.1  , -0.1  ,  0.125, -0.1  ],
       [-0.1  , -0.1  , -0.1  ,  0.125]])

In [ ]:
tarea cuanto vale 0 a la 0 y porque