###### 

In [1]:
import numpy as np

In [5]:
## convetir datos a arreglos
value = np.array({5, 'string'})
print (f'value = {value}, data type = {type(value)}')

value = {'string', 5}, data type = <class 'numpy.ndarray'>


In [8]:
range(4)

range(0, 4)

In [11]:
np.array(range(-7, 6))

array([-7, -6, -5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [12]:
##  para quedarnos de -5 a -2
np.array(range(-7, 6))[2:6]

array([-5, -4, -3, -2])

In [13]:
a, b= np.arange(5), np.arange(-10, -5)
a, b

(array([0, 1, 2, 3, 4]), array([-10,  -9,  -8,  -7,  -6]))

In [14]:
b-a

array([-10, -10, -10, -10, -10])

In [15]:
b/3

array([-3.33333333, -3.        , -2.66666667, -2.33333333, -2.        ])

In [16]:
a + 18

array([18, 19, 20, 21, 22])

In [17]:
a - b

array([10, 10, 10, 10, 10])

In [18]:
a * b
#matematicamente no existe el producto de vectores 

array([  0,  -9, -16, -21, -24])

In [19]:
b / a
## -inf es infinito

C:\Users\HP\AppData\Local\Temp\ipykernel_31756\1491818542.py:1: RuntimeWarning: divide by zero encountered in divide
  b / a


array([       -inf, -9.        , -4.        , -2.33333333, -1.5       ])

In [20]:
b ** (1/a)
## los nan no son invalidos, solo no fue capaz de ejecutarlo por el tipo de datos, ojo con los warning 

C:\Users\HP\AppData\Local\Temp\ipykernel_31756\1878905493.py:1: RuntimeWarning: divide by zero encountered in divide
  b ** (1/a)
C:\Users\HP\AppData\Local\Temp\ipykernel_31756\1878905493.py:1: RuntimeWarning: invalid value encountered in power
  b ** (1/a)


array([inf, -9., nan, nan, nan])

In [32]:
(64) ** (1/4)

2.8284271247461903

In [31]:
(27) ** (1/3)

3.0

In [27]:
(-8)** 0.5

(1.7319121124709868e-16+2.8284271247461903j)

In [33]:
(-8)** (1/2)

(1.7319121124709868e-16+2.8284271247461903j)

In [36]:
vec= np.array ([5,10])
vec

array([ 5, 10])

In [38]:
vec. transpose()

array([ 5, 10])

In [48]:
vec2D= np.array([[4, -1], [-7, 2]])
vec2D

array([[ 4, -1],
       [-7,  2]])

In [49]:
vec2D.transpose(), vec2D.T

(array([[ 4, -7],
        [-1,  2]]),
 array([[ 4, -7],
        [-1,  2]]))

In [50]:
vec1= np.array([[1, 2], [3, 4]])
vec1, vec2D

(array([[1, 2],
        [3, 4]]),
 array([[ 4, -1],
        [-7,  2]]))

In [52]:
resultado = vec1 @ vec2D
resultado

array([[-10,   3],
       [-16,   5]])

In [59]:
resultado [1][0]

np.int64(-16)

In [60]:
resultado [1]

array([-16,   5])

In [62]:
matriz = np.array ([[0,5,10],
                    [15,20,25],
                    [99,35,40]])

In [64]:
matriz [2][:-1]

array([99, 35])

In [67]:
matriz [2][:2]

array([99, 35])

In [68]:
matriz [:][:]

array([[ 0,  5, 10],
       [15, 20, 25],
       [99, 35, 40]])

In [80]:
matriz [1:][:]

array([[15, 20, 25],
       [99, 35, 40]])

In [81]:
matriz [1:]

array([[15, 20, 25],
       [99, 35, 40]])

### tarea 
tener la columna de en medio

In [92]:
matriz [0,1]

np.int64(5)

In [86]:
matriz[1][0]=-20
matriz
## es mutable

array([[  0,   5,  10],
       [-20,  20,  25],
       [ 99,  35,  40]])

In [88]:
for _ in range (5):
    print (np.random.rand())

## esto ejecuta numeros aleatorios entre el cero y uno 

0.8962307651466196
0.5053457243771797
0.2898833424501335
0.7410572498088966
0.5924095072486852


In [93]:
np.random.rand(5,3)

array([[0.09285685, 0.84775871, 0.45974872],
       [0.70103165, 0.9800986 , 0.35593888],
       [0.47122481, 0.65116194, 0.34071412],
       [0.61844674, 0.7277248 , 0.43567272],
       [0.78575431, 0.48315947, 0.26484336]])

In [ ]:
## distribucion uniforme es la de dados, siempre es la misma probabilidad es recta 