In [3]:
import numpy as np

In [5]:
# Convertir datos a arreglos 
value=np.array({5, 'string'})
print(f'value={value}, data type = {type(value)}')

value={'string', 5}, data type = <class 'numpy.ndarray'>


In [6]:
np.array(range(4))

array([0, 1, 2, 3])

In [138]:
matriz= np.array([[0, 5, 10],
                [15, 20, 25],
                [99, 35, 40]])
matriz

array([[ 0,  5, 10],
       [15, 20, 25],
       [99, 35, 40]])

In [139]:
matriz[:][2]

array([99, 35, 40])

In [140]:
matriz[:][:]

array([[ 0,  5, 10],
       [15, 20, 25],
       [99, 35, 40]])

In [141]:
matriz[1][:-2]

array([15])

In [186]:
matriz[:][1][1]

np.int64(20)

In [205]:
matriz[:,1]

array([ 5, 20, 35])