In [1]:
from cosas import *

In [2]:
saludo()

holaaaaaa


In [3]:
funcion ()

otra funcion


In [4]:
suma(2, 3)

5

# Paquete numpy
Es un paquete enfocado en manipular información en estructuras conocidas para vectores, arreglo y matrices. 
La contribución más significativa del paquete numpoy es la introducción de un tipo de dato llamado array

In [10]:
import numpy as np

In [11]:
lista = [3,4,5]
variable = np.array(lista)
type(variable)

numpy.ndarray

In [12]:
variable

array([3, 4, 5])

In [21]:
variable.ndim, variable.shape

(1, (3,))

In [22]:
variable2d = np.array([
    [4, 5, 6],
    [7, 8, 9]
])
type(variable2d), variable2d.ndim, variable2d.shape


(numpy.ndarray, 2, (2, 3))

In [20]:
variable2d.shape

(2, 3)

### Funciones de numpy

In [24]:
np.zeros(6),np.zeros([3, 4])

(array([0., 0., 0., 0., 0., 0.]),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]))

In [26]:
np.ones(4), np.ones([2,3,4])

(array([1., 1., 1., 1.]),
 array([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],
 
        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]))

In [28]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#Ejercicio. Crear un arreglo de 4x4 cuyos elementos en la diagonal sean iguales a 8, pero fuera de la diagonal sea igual a -10

In [44]:
8*np.eye(4)

array([[8., 0., 0., 0.],
       [0., 8., 0., 0.],
       [0., 0., 8., 0.],
       [0., 0., 0., 8.]])

In [46]:
valor = -10*np.ones([4,4])+ 18*np.eye(4)
valor

array([[  8., -10., -10., -10.],
       [-10.,   8., -10., -10.],
       [-10., -10.,   8., -10.],
       [-10., -10., -10.,   8.]])

In [47]:
valor/2

array([[ 4., -5., -5., -5.],
       [-5.,  4., -5., -5.],
       [-5., -5.,  4., -5.],
       [-5., -5., -5.,  4.]])

In [39]:
10*[1, 1, 1]

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1]

In [48]:
1/valor

array([[ 0.125, -0.1  , -0.1  , -0.1  ],
       [-0.1  ,  0.125, -0.1  , -0.1  ],
       [-0.1  , -0.1  ,  0.125, -0.1  ],
       [-0.1  , -0.1  , -0.1  ,  0.125]])