In [1]:
from modulo import *

In [2]:
saludo()

hola desde el paquete


In [4]:
function()

otra funcion


In [5]:
suma (2, 3)

5

In [6]:
import numpy

# PAQUETE numpy

es un paquete enfocado en manipular la información en estructuras conocidas como vectores, arreglo y matrices.

la contribución más significativa del paquete numpy es la introdución de un tipo de dato llamado array 

In [7]:
import numpy as np 

In [8]:
lista = [3,4,5]

variable = np.array(lista) 
type(variable)

numpy.ndarray

In [12]:
variable.ndim, variable.shape

(1, (3,))

In [15]:
variable2d = np.array([
    [4,5,6],
    [7,8,9]
])
type(variable2d), variable2d.ndim, variable2d.shape

(numpy.ndarray, 2, (2, 3))

In [16]:
variable2d.shape

(2, 3)

# funciones numpy

In [18]:
np.zeros(6), np.zeros ([3,4])

(array([0., 0., 0., 0., 0., 0.]),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]))

In [20]:
np.ones(4), np.ones([2,3,4])

(array([1., 1., 1., 1.]),
 array([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],
 
        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]))

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
# Ejercicio crear un arreglo de 4x4 cuyos ele,mentos en la diagonal sena igual a 8 
# pero fuera de la diagonal sean igual a -10

In [24]:
import numpy as np

matriz = np.full((4, 4), -10)

np.fill_diagonal(matriz, 8)

print(matriz)

[[  8 -10 -10 -10]
 [-10   8 -10 -10]
 [-10 -10   8 -10]
 [-10 -10 -10   8]]


In [25]:
-10*np.ones([4,4]) + 18*np.eye(4)

array([[  8., -10., -10., -10.],
       [-10.,   8., -10., -10.],
       [-10., -10.,   8., -10.],
       [-10., -10., -10.,   8.]])

In [27]:
np.eye(4)*8

array([[8., 0., 0., 0.],
       [0., 8., 0., 0.],
       [0., 0., 8., 0.],
       [0., 0., 0., 8.]])

In [28]:
valor = -10*np.ones([4,4])+ 18*np.eye(4)

In [29]:
valor/2

array([[ 4., -5., -5., -5.],
       [-5.,  4., -5., -5.],
       [-5., -5.,  4., -5.],
       [-5., -5., -5.,  4.]])

In [30]:
1/valor

array([[ 0.125, -0.1  , -0.1  , -0.1  ],
       [-0.1  ,  0.125, -0.1  , -0.1  ],
       [-0.1  , -0.1  ,  0.125, -0.1  ],
       [-0.1  , -0.1  , -0.1  ,  0.125]])