In [1]:
# mandar a llamar todas las funciones con *
from modulo import *

In [2]:
saludo()

hola desde el paquete


In [3]:
funcion()

otra función


In [4]:
suma(2,3)

5

# Paquete numpy
 es un paquete enfocado en manipular infrmación en estructuras conocidas como vectores, arreglo y matrices.
 
 La contribución más significativa del paquete numpy es la introducción de un tipo de dato llamado __array__

In [8]:
import numpy as np

In [6]:
!pip install numpy pandas matplotlib

     --------------------------------------- 13.1/13.1 MB 28.5 MB/s eta 0:00:00
     --------------------------------------- 11.3/11.3 MB 28.4 MB/s eta 0:00:00
     ---------------------------------------- 8.1/8.1 MB 24.7 MB/s eta 0:00:00
     ------------------------------------- 509.2/509.2 kB 16.1 MB/s eta 0:00:00
     -------------------------------------- 347.8/347.8 kB 1.7 MB/s eta 0:00:00
     ------------------------------------- 225.2/225.2 kB 14.3 MB/s eta 0:00:00
     ---------------------------------------- 2.3/2.3 MB 18.0 MB/s eta 0:00:00
     ---------------------------------------- 73.8/73.8 kB 4.2 MB/s eta 0:00:00
     ---------------------------------------- 7.0/7.0 MB 22.4 MB/s eta 0:00:00
     -------------------------------------- 111.1/111.1 kB 6.7 MB/s eta 0:00:00



[notice] A new release of pip available: 22.3.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [9]:
lista= [3,4,5]
variable=np.array(lista)
type(variable)

numpy.ndarray

In [20]:
#numpy: arreglos, matrices, ndim ver dimensión
variable.ndim, variable.shape

(1, (3,))

In [21]:
# arreglo bidimensional, en python todos son arreglos
variable2d= np.array([
    [4,5,6],
    [7,8,9]
])



In [22]:
# metodos: poner en parentesis y propiedades; no necesita parentesis
# .shape indica filas, columnas
type(variable2d),variable2d.ndim,variable2d.shape

(numpy.ndarray, 2, (2, 3))

### funciones de numpy

In [24]:
#arreglo de ceros
np.zeros(6), np.zeros([3,4])

(array([0., 0., 0., 0., 0., 0.]),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]))

In [26]:
# arreglos de unos
np.ones(4),np.ones([2,3,4])

(array([1., 1., 1., 1.]),
 array([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],
 
        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]))

In [28]:
# matriz de identidad(tiene que ser una ,atiz cuadrada), elementos en diagonal=1, fuera de ella=0
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Ejercicio, crear un arreglo de 4x4 cuyos elementos en la diagoal sean =8 pero fuera de la diagonal= -10

In [42]:
valor= -10*np.ones([4,4])  +18*np.eye(4)

In [45]:
1/valor

array([[ 0.125, -0.1  , -0.1  , -0.1  ],
       [-0.1  ,  0.125, -0.1  , -0.1  ],
       [-0.1  , -0.1  ,  0.125, -0.1  ],
       [-0.1  , -0.1  , -0.1  ,  0.125]])

In [ ]:
valor