In [8]:
import modulo

In [9]:
saludo()

hola desde el paquete


In [10]:
funcion()

otra funcion


In [11]:
suma(2, 3)

5

# Paquete numpy

Es un paquete enfocado en manipular información en estructuras conocidas como vectores, arreglo y matrices.

La contribución más significativa del paquete numpy es la introducción de un tipo de dato llamado __array__

In [14]:
import numpy as np

In [15]:
lista = [3, 4, 5]

variable = np.array(lista)
type(variable)

numpy.ndarray

In [16]:
variable

array([3, 4, 5])

In [23]:
variable.ndim, variable.shape

(1, (3,))

In [24]:
variable2d = np.array([
    [4, 5, 6], 
    [7, 8, 9]
])
type(variable2d), variable2d.ndim, variable2d.shape

(numpy.ndarray, 2, (2, 3))

In [22]:
variable2d.shape

(2, 3)

### funciones de numpy

In [29]:
np.zeros(6), np.zeros((3, 4))

(array([0., 0., 0., 0., 0., 0.]),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]))

In [31]:
np.ones(4), np.ones([2, 3, 4])

(array([1., 1., 1., 1.]),
 array([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],
 
        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]))

In [33]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Ejercicio. Crear un arreglo de 4x4 cuyos elementos en la diagonal sean igual a 8 
# pero fuera de la diagonal sea igual a -10 

In [41]:
valor = -10*np.ones([4, 4]) + 18*np.eye(4)
valor

array([[  8., -10., -10., -10.],
       [-10.,   8., -10., -10.],
       [-10., -10.,   8., -10.],
       [-10., -10., -10.,   8.]])

In [45]:
valor**0.5

C:\Users\OMEN CI7\AppData\Local\Temp\ipykernel_11588\1006119973.py:1: RuntimeWarning: invalid value encountered in sqrt
  valor**0.5


array([[2.82842712,        nan,        nan,        nan],
       [       nan, 2.82842712,        nan,        nan],
       [       nan,        nan, 2.82842712,        nan],
       [       nan,        nan,        nan, 2.82842712]])

In [48]:
valor

array([[  8., -10., -10., -10.],
       [-10.,   8., -10., -10.],
       [-10., -10.,   8., -10.],
       [-10., -10., -10.,   8.]])

In [47]:
1/valor

array([[ 0.125, -0.1  , -0.1  , -0.1  ],
       [-0.1  ,  0.125, -0.1  , -0.1  ],
       [-0.1  , -0.1  ,  0.125, -0.1  ],
       [-0.1  , -0.1  , -0.1  ,  0.125]])