# Paquete numpy

propiedad no lleva paréntesis
método lleva paréntesis

In [3]:
import numpy as np  # importar los paquetes que vamos a utilizar

In [4]:
# convertir datos a arreglos

value = np.array({5, "string"})

print(f"value = {value}, data type = {type(value)}")

value = {5, 'string'}, data type = <class 'numpy.ndarray'>


In [8]:
# se puede aplicar el slicing, ya que son objetos iterables. 

np.array(range(-7, 6))[2:6] 

array([-5, -4, -3, -2])

### Operaciones con arrays

In [10]:
a, b = np.arange(5), np.arange(-10, -5)
a,b 

(array([0, 1, 2, 3, 4]), array([-10,  -9,  -8,  -7,  -6]))

In [11]:
a + b

array([-10,  -8,  -6,  -4,  -2])

In [12]:
b-a

array([-10, -10, -10, -10, -10])

In [13]:
6  * a

array([ 0,  6, 12, 18, 24])

In [14]:
b / 3

array([-3.33333333, -3.        , -2.66666667, -2.33333333, -2.        ])

In [17]:
a * b

array([  0,  -9, -16, -21, -24])

In [20]:
b**a

array([   1,   -9,   64, -343, 1296])

In [28]:
b**(1/a)

# nan = not a number
# en este caso las operaciones si se pueden hacer, pero no en los arreglos

/var/folders/48/5mv2c8bn0mn_vl9c6chb0flm0000gp/T/ipykernel_22426/1607177895.py:1: RuntimeWarning: divide by zero encountered in divide
  b**(1/a)
/var/folders/48/5mv2c8bn0mn_vl9c6chb0flm0000gp/T/ipykernel_22426/1607177895.py:1: RuntimeWarning: invalid value encountered in power
  b**(1/a)


array([inf, -9., nan, nan, nan])

In [29]:
# no es un error numérico si no uno en numpy
-6**(1/4)

-1.5650845800732873

In [30]:
vec = np.array([5, 10])
vec

array([ 5, 10])

In [31]:
# para transponer .transpose()
vec.transpose()

array([ 5, 10])

In [33]:
vec2D = np.array([[4, -1], [-7, 2]])
vec2D

array([[ 4, -1],
       [-7,  2]])

In [35]:
# con método .transpose() o la propiedad .T
vec2D.transpose(), vec2D.T

(array([[ 4, -7],
        [-1,  2]]),
 array([[ 4, -7],
        [-1,  2]]))

In [38]:
vec_2D = np.array([[1,2], [3, 4]])
vec_2D, vec2D

(array([[1, 2],
        [3, 4]]),
 array([[ 4, -1],
        [-7,  2]]))

In [41]:
# utilizando el @ hacemos un producto matricial --> se multiplican filas por columnas
resultado = vec_2D @ vec2D
resultado

array([[-10,   3],
       [-16,   5]])

In [45]:
# doble slicing --> hacer el slicing de un slicing
resultado[1][0]

np.int64(-16)

In [44]:
resultado[1]

array([-16,   5])

In [48]:
matriz = np.array([[0, 5, 10],
                  [15, 20, 25],
                  [99, 35, 40]])
matriz

array([[ 0,  5, 10],
       [15, 20, 25],
       [99, 35, 40]])

In [50]:
# para quedarme con 5
matriz[0][1]

np.int64(5)

In [56]:
# para tener 99 y 35
matriz[2][:-1] # o [:2]

array([99, 35])

In [57]:
matriz[:][:]

array([[ 0,  5, 10],
       [15, 20, 25],
       [99, 35, 40]])

In [58]:
# las dos últimas filas
matriz[1:]

array([[15, 20, 25],
       [99, 35, 40]])

### Tarea

Quedarme con la columna del medio

In [60]:
# estoy cambiando el 15
matriz[1][0] = -20
matriz

array([[  0,   5,  10],
       [-20,  20,  25],
       [ 99,  35,  40]])

para generar números aleatorios usamos la clase .random.

clase es equivalente a un módulo

In [61]:
# .rand() --> valores entre 0 y 1
for _ in range (5):
    print(np.random.rand())

0.29322167335525895
0.6631778848694065
0.31764996787339317
0.3849584935473368
0.2284281125246913


In [65]:
np.random.rand(5, 3) # nos lo regresa como un arreglo, este puede ser multidimensional

array([[0.58448885, 0.73673564, 0.24304634],
       [0.97478225, 0.88964142, 0.88007194],
       [0.89497765, 0.22919669, 0.40230283],
       [0.68125378, 0.72996664, 0.11894534],
       [0.45129105, 0.45034595, 0.80317327]])