In [2]:
import numpy as np

In [6]:
#convertir datos a arreglos 
value = np.array ({5, "string"})
print (f"value = {value}, data type= {type(value)}")

value = {5, 'string'}, data type= <class 'numpy.ndarray'>


In [13]:
np.array(range(-7,6)) [2:6]


array([-5, -4, -3, -2])

In [22]:
a,b = np.arange(5), np.arange(-10,-5)
a,b

(array([0, 1, 2, 3, 4]), array([-10,  -9,  -8,  -7,  -6]))

In [25]:
a * b

array([  0,  -9, -16, -21, -24])

In [31]:
matriz = np.array ([[0, 5, 10],
                    [15, 20, 25],
                    [99,35,40]])

In [36]:
matriz[0:2][1]

array([15, 20, 25])