In [1]:
from package import *

In [2]:
saludo()

hola desde el paquete


In [3]:
funcion()

otra funcion 


In [4]:
suma(2,3)

5

In [7]:
import numpy as np

In [8]:
lista = [3,4,5]

variable = np.array(lista)
type(variable)

numpy.ndarray

In [9]:
# Paquete numpy 
Es un pquete enfoado en mainpular info en estructuras conocias como vectores, arreglo y matrices.

La contribucion mas significatiba del paquete numpy es la introduccion de un tipo de dato llamado array 

SyntaxError: invalid syntax (1564196859.py, line 2)

In [10]:
variable2d = np.array([ 
    [4,5,6],
    [7,8,9]])
type(variable2d), variable2d.ndim, variable2d.shape


(numpy.ndarray, 2, (2, 3))

In [13]:
numpy.ndarray,(2 (2,3))

<>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<>:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
C:\Users\980041133\AppData\Local\Temp\ipykernel_20052\3021142847.py:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  numpy.ndarray,(2 (2,3))
C:\Users\980041133\AppData\Local\Temp\ipykernel_20052\3021142847.py:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  numpy.ndarray,(2 (2,3))
C:\Users\980041133\AppData\Local\Temp\ipykernel_20052\3021142847.py:1: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  numpy.ndarray,(2 (2,3))


NameError: name 'numpy' is not defined

In [14]:
variable.shape

(3,)

In [15]:
Funciones de numpy 

SyntaxError: invalid syntax (480320040.py, line 1)

In [16]:
np.zeros(6) , np.zeros([3,4])

(array([0., 0., 0., 0., 0., 0.]),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]))

In [17]:
np.ones(4), np.ones([2,3,4])

(array([1., 1., 1., 1.]),
 array([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],
 
        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]))

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
#Ejercicio. Crear un arreglo de 4x4 cuyos elementos en la diagonal sean igual a 8 
#pero fuera de la diagonal sea igual a -10
Valor =-10*np.ones([4,4])

In [23]:
Valor/2

array([[-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.],
       [-5., -5., -5., -5.]])

In [24]:
1/Valor

array([[-0.1, -0.1, -0.1, -0.1],
       [-0.1, -0.1, -0.1, -0.1],
       [-0.1, -0.1, -0.1, -0.1],
       [-0.1, -0.1, -0.1, -0.1]])

In [ ]:
#las matrices tienen su arreglo 
# pero python 
