In [2]:
import numpy as np

In [4]:
# convertir datos a arreglos
value = np.array({5, 'string'})
print(f"Value = {value}, data type = {type(value)}")

Value = {'string', 5}, data type = <class 'numpy.ndarray'>


In [8]:
np.array(range(-7, 6))[2:6]

array([-5, -4, -3, -2])

In [12]:
a, b = np.arange(5), np.arange(-10, -5)
a, b

(array([0, 1, 2, 3, 4]), array([-10,  -9,  -8,  -7,  -6]))

In [13]:
a + b

array([-10,  -8,  -6,  -4,  -2])

In [14]:
b - a

array([-10, -10, -10, -10, -10])

In [15]:
6*a

array([ 0,  6, 12, 18, 24])

In [16]:
b/3

array([-3.33333333, -3.        , -2.66666667, -2.33333333, -2.        ])

In [17]:
a + 18

array([18, 19, 20, 21, 22])

In [18]:
a - 18

array([-18, -17, -16, -15, -14])

In [19]:
a * b

array([  0,  -9, -16, -21, -24])

In [20]:
b/a

C:\Users\V304-18\AppData\Local\Temp\ipykernel_8364\2243761560.py:1: RuntimeWarning: divide by zero encountered in divide
  b/a


array([       -inf, -9.        , -4.        , -2.33333333, -1.5       ])

In [21]:
a**2
# al cuadrado

array([ 0,  1,  4,  9, 16])

In [23]:
a**(1/2)
# raiz cuadrada

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [25]:
b**a
# elevarlo potencia

array([   1,   -9,   64, -343, 1296])

In [26]:
b**(1/a)

C:\Users\V304-18\AppData\Local\Temp\ipykernel_8364\3261360213.py:1: RuntimeWarning: divide by zero encountered in divide
  b**(1/a)
C:\Users\V304-18\AppData\Local\Temp\ipykernel_8364\3261360213.py:1: RuntimeWarning: invalid value encountered in power
  b**(1/a)


array([inf, -9., nan, nan, nan])

In [27]:
(-6)**(-5)

-0.0001286008230452675

In [28]:
27**(1/3)

3.0

In [29]:
121**(1/2)

11.0

In [30]:
vec = np.array([5, 10])
vec

array([ 5, 10])

In [31]:
vec.transpose()

array([ 5, 10])

In [34]:
vec2D = np.array([[4, -1], [-7, 2]])
vec2D

array([[ 4, -1],
       [-7,  2]])

In [35]:
vec2D.transpose(), vec2D.T

(array([[ 4, -7],
        [-1,  2]]),
 array([[ 4, -7],
        [-1,  2]]))

In [38]:
vec1 = np.array([[1, 2], [3, 4]])
vec1, vec2D

(array([[1, 2],
        [3, 4]]),
 array([[ 4, -1],
        [-7,  2]]))

In [40]:
resultado = vec1 @ vec2D
resultado

array([[-10,   3],
       [-16,   5]])

In [50]:
resultado [1][0]

np.int64(-16)

In [52]:
matriz = np.array([[0, 5, 10], [15, 20, 25], [99, 35, 40]])

In [53]:
matriz [0][1]

np.int64(5)

In [54]:
matriz [2][0:-1]

array([99, 35])

In [55]:
matriz [:][:]

array([[ 0,  5, 10],
       [15, 20, 25],
       [99, 35, 40]])

In [58]:
matriz[1:]

array([[15, 20, 25],
       [99, 35, 40]])

In [59]:
matriz [1][0] = -20
matriz

array([[  0,   5,  10],
       [-20,  20,  25],
       [ 99,  35,  40]])

# tarea
Quedarme con la columna de en medio 

In [60]:
for _ in range(5): 
    print(np.random.rand()) #generar numeros aleatorios entr 0 y 1

0.879356293045676
0.38974687055224344
0.7216659070629396
0.2787954526335352
0.133968912966278


In [64]:
np.random.rand(5, 3)

array([[0.14235709, 0.58049234, 0.70229651],
       [0.67564832, 0.2674823 , 0.82463439],
       [0.51851524, 0.76358753, 0.39521963],
       [0.29876088, 0.86684176, 0.65462146],
       [0.57245184, 0.53578137, 0.56499533]])