In [3]:
from modulo import *

In [4]:
saludos()

Holiwissss Polinesiosssssss


In [5]:
funcion()

otra funcion


In [6]:
suma(2, 3)

5


In [1]:
import numpy as np


In [ ]:
numpy.

### Paquete numpy

Es un paquete enfocado en manipular informacion en estructuras conocidas como vectores, arreglo y matrices.

La contribucion mas significativa del paquete numpy es laintroduccion de un  tipo de dato llamado array. 

In [17]:
lista = [3,4,5]

variable = np.array(lista)
type(variable) 

numpy.ndarray

In [18]:
variable

array([3, 4, 5])

In [19]:
variable.ndim

1

In [27]:
variable2d = np.array([
    [4, 5, 6],
    [7, 8, 9]
])

type(variable2d), variable2d.ndim, variable2d.shape

# Arreglos en python, matrices en matlab


(numpy.ndarray, 2, (2, 3))

In [25]:
variable2d

array([[4, 5, 6],
       [7, 8, 9]])

In [26]:
variable2d.shape

(2, 3)

 # Funciones de numpy

In [33]:
np.zeros(6), np.zeros([3,4])

(array([0., 0., 0., 0., 0., 0.]),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]))

In [34]:
np.ones(4), np.ones([])

(array([1., 1., 1., 1.]), array(1.))

In [38]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#Ejercicio. Crear un arreglo de 4x4 cuyos elementos sean igual a 8 pero fuera de la diagonal sea igual a -10

In [60]:
valor = -10*np.ones([4, 4]) + 18*np.eye(4)
valor

array([[  8., -10., -10., -10.],
       [-10.,   8., -10., -10.],
       [-10., -10.,   8., -10.],
       [-10., -10., -10.,   8.]])

In [61]:
valor/2

array([[ 4., -5., -5., -5.],
       [-5.,  4., -5., -5.],
       [-5., -5.,  4., -5.],
       [-5., -5., -5.,  4.]])

In [62]:
10* [1,1,1]

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1]

In [63]:
1/valor

array([[ 0.125, -0.1  , -0.1  , -0.1  ],
       [-0.1  ,  0.125, -0.1  , -0.1  ],
       [-0.1  , -0.1  ,  0.125, -0.1  ],
       [-0.1  , -0.1  , -0.1  ,  0.125]])