In [3]:
from modulo import *

In [5]:
saludo()

Hola!!!!!


In [6]:
funcion()

otra función


In [7]:
suma (2, 3)

5

### Paquete numpy
Es un paquete enfocado en manipular información en estructuras conocidas como vectore, arreglo y matrices.

La contribución más significativa del paquete numpy es la introducción de un tipo de dato llmado _array_

In [15]:
import numpy as np

In [16]:
lista = [3, 4, 5]

variable = np.array(lista)
type(variable)

numpy.ndarray

In [17]:
variable

array([3, 4, 5])

In [18]:
variable.ndim

1

In [31]:
variable2d = np.array([
    [4,5,6],
    [7, 8, 9]
])
type(variable2d), variable2d.ndim, variable2d.shape
# Arreglos en python, matrices en matlab

(numpy.ndarray, 2, (2, 3))

In [32]:
variable2d

array([[4, 5, 6],
       [7, 8, 9]])

In [33]:
variable.ndim

1

In [34]:
variable.shape

(3,)

### Funciones de numpy

In [36]:
np.zeros(6), np.zeros([3, 4])

(array([0., 0., 0., 0., 0., 0.]),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]))

In [38]:
np.ones(4), np.ones([2, 3, 4])

(array([1., 1., 1., 1.]),
 array([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],
 
        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]))

In [40]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
# Ejercicio. Crear un arreglo de 4x4 cuyos elementos sean igual a 8 pero fuera de la diagonal sea igual a -10

In [49]:
np.ones(4), np.ones([2,2]), 

(array([1., 1., 1., 1.]),
 array([[1., 1.],
        [1., 1.]]))

In [53]:
valor = -10*np.ones([4,4]) + 18*np.eye(4)
valor

array([[  8., -10., -10., -10.],
       [-10.,   8., -10., -10.],
       [-10., -10.,   8., -10.],
       [-10., -10., -10.,   8.]])

In [52]:
10*[1, 1, 1, 1]

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1]

In [57]:
valor**0.5

C:\Users\V304-18\AppData\Local\Temp\ipykernel_3556\1006119973.py:1: RuntimeWarning: invalid value encountered in sqrt
  valor**0.5


array([[2.82842712,        nan,        nan,        nan],
       [       nan, 2.82842712,        nan,        nan],
       [       nan,        nan, 2.82842712,        nan],
       [       nan,        nan,        nan, 2.82842712]])

In [54]:
valor/2

array([[ 4., -5., -5., -5.],
       [-5.,  4., -5., -5.],
       [-5., -5.,  4., -5.],
       [-5., -5., -5.,  4.]])

In [56]:
1/valor

array([[ 0.125, -0.1  , -0.1  , -0.1  ],
       [-0.1  ,  0.125, -0.1  , -0.1  ],
       [-0.1  , -0.1  ,  0.125, -0.1  ],
       [-0.1  , -0.1  , -0.1  ,  0.125]])