## Modulos
¿que es un modulo?
es un script que contiene varaibles, funciones y clases
1) hacer un bloc de notas con la función
2) guardar en formato .py
3) from __ nombre archivo__ import * (importa todo lo que viene en el bloc de notas)
4) si quiero solo llamar una en especifico pongo el nombre de la función que quiero llamar
5) despues de cargarlas, ya puedo llamarlas

In [11]:
from funcion_buena import * 

In [12]:
saludo()

Hola


## Paquete numpy
es un paquete enfocado en manipular arreglos de n dimensiones, es decir un arreglo. Un arreglo es una lista numerico con una sola dimension Numpy no hace ecuaciones matematicas


In [13]:
import numpy as np

In [14]:
lista= [3,4,5]

variable=np.array(lista) # a esta variable hazmela un arreglo
type(variable)

numpy.ndarray

In [15]:
var2=np.array([
    [4,5,6],
    [7,8,9]
])
type(var2), var2.ndim ##cuantas dimensiones tiene mi variable

(numpy.ndarray, 2)

In [16]:
var2

array([[4, 5, 6],
       [7, 8, 9]])

In [17]:
var2.shape # los arreglos tmb tiene forma, dos filas 3 colunmans 

(2, 3)

## funciones de numpy

In [18]:
np.zeros(20), np.zeros([3,4]) ##arreglo de puros ceros, tú argumento son el número de ceros

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.]),
 array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]))

In [19]:
np.ones([4,3,3, 3, 3]) ##arreglos de puros unos

array([[[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]],



       [[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
    

In [20]:
np.eye(3) ##función para crear una matriz de identidad, recordar q las matricez de identidad tienen q ser cuadradois

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.eye(5) ## crea una matriz de 5*5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
## crar un arreglo de 4x4 cuyos elementos en la diagonal sean=8 y los de afuera=-10

In [22]:
valor= -10*np.ones([4,4])+ 18*np.eye(4) ##puedes sumar arregles, -10+18= 8
print(valor)

[[  8. -10. -10. -10.]
 [-10.   8. -10. -10.]
 [-10. -10.   8. -10.]
 [-10. -10. -10.   8.]]


In [23]:
np.eye(4)*8## puedes multiplicar los argumentos de los arreglos

array([[8., 0., 0., 0.],
       [0., 8., 0., 0.],
       [0., 0., 8., 0.],
       [0., 0., 0., 8.]])

In [24]:
np.eye(4)*8## puedes multiplicar los argumentos de los arreglos

array([[8., 0., 0., 0.],
       [0., 8., 0., 0.],
       [0., 0., 8., 0.],
       [0., 0., 0., 8.]])

In [25]:
valor/2 ### los arreglos se pueden dividir

array([[ 4., -5., -5., -5.],
       [-5.,  4., -5., -5.],
       [-5., -5.,  4., -5.],
       [-5., -5., -5.,  4.]])

In [26]:
valor**2

array([[ 64., 100., 100., 100.],
       [100.,  64., 100., 100.],
       [100., 100.,  64., 100.],
       [100., 100., 100.,  64.]])

In [27]:
1/valor

array([[ 0.125, -0.1  , -0.1  , -0.1  ],
       [-0.1  ,  0.125, -0.1  , -0.1  ],
       [-0.1  , -0.1  ,  0.125, -0.1  ],
       [-0.1  , -0.1  , -0.1  ,  0.125]])